### ISSUE TITLE
2번째 : 스케줄러의 종류, CPU 스케줄러

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#1]
다음 스터디 일자 : 2022-01-13 (목)

# 이번 주제 

- 스케줄러의 종류
  - 장기 스케줄러
  - 단기 스케줄러
  - 중기 스케줄러
- CPU 스케줄러
  - FCFS
  - SJF
  - SRT
  - Priority scheduling
  - RR

**Comment by choiyoungkwon12** [comment]
- cpu 스케줄링에서 선점, 비선점 방식의 차이는 무엇인가요?
  - 선점형 방식은 CPU를 다른 프로세스가 사용하고 있더라도 우선순위에 따라 우선순위가 높은 프로세스가 자원을 할당받을 수 있다.
  - 비선점형 방식은 CPU를 획득한 프로세스가 스스로 CPU를 반납하기 전까지 CPU를 빼앗기지 않는 방법

- 프로세스 상태에서 Ready와 wait의 차이점은 무엇인가요?
   - Ready는 프로세스가 생성된 후 준비상태가 되어 CPU자원을 할당 받았을 때 실행될 수 있는 상태
   - Wait는 프로세스가 I/O에 대한 작업이 필요하거나 임계영역에 대한 작업을 기다리거나 할때 Block or Wait 상태가 됩니다.
- cpu 스케줄링에서 기아 현상과 해결법은 무엇인가요?
   - 선점형 방식에서 우선순위가 낮은 프로세스가 계속 cpu 자원을 할당받지 못하는 현상을 기아 현상이라고 합니다.
   - 해결법은 대기시간에 따라 프로세스의 우선순위를 높여 cpu 자원을 할당 받을 수 있게 하는 에이징이 있습니다.

**Comment by Chaeonida** [comment]
- 장기, 단기, 중기 스케줄링 각각의 특징은 무엇인가요?

   장기스케줄러는 메모리는 한정되어 있는데 많은 프로세스들이 한꺼번에 메모리에 올라올 경우, 대용량 메모리(일반적으로 디스크)에 임시로 저장된다. 이 pool 에 저장되어 있는 프로세스 중 어떤 프로세스에 메모리를 할당하여 ready queue 로 보낼지 결정하는 역할을 한다. 
  단기스케줄러는 실행이 준비된 프로세스들 중 하나를 선별해 CPU에게 할당하는 역할을 하고 
   중기스케줄러는 여유 공간 마련을 위해 프로세스를  메모리에서 디스크로 스와핑 하는 역할을 한다. 

- CPU 스케줄링 알고리즘의 목적은 무엇인가요?

   No starvation : 각각의 프로세스들이 오랜시간동안 CPU를 할당받지 못하는 상황이 없도록 한다.
   Fairness : 각각의 프로세스에 공평하게 CPU를 할당해준다.
   Balance : Keeping all parts of the system busy

- 우선 순위 스케줄링은 무엇인가요?

우선순위가 가장 높은 프로세스에게 CPU 를 할당하는 스케줄링이다. 우선순위란 정수로 표현하게 되고 작은 숫자가 우선순위가 높다.선점형 스케줄링(Preemptive) 방식과 비선점형 스케줄링(Non-Preemptive) 방식이 있고 전자는 더 높은 우선순위의 프로세스가 도착하면 실행중인 프로세스를 멈추고 CPU 를 선점한다.후자는 더 높은 우선순위의 프로세스가 도착하면 Ready Queue 의 Head 에 넣는다.
문제점으로는 실행 준비는 되어있으나 CPU 를 사용못하는 프로세스를 CPU 가 무기한 대기하는 상태인 기아상태가 발생할 수 있고, 해결방법으로는 아무리 우선순위가 낮은 프로세스라도 오래 기다리면 우선순위를 높여주는 에이징 기법이 있다.

**Comment by jerry0339** [comment]
* **스케줄러의 종류와 가상메모리는 어떤 연관성이 있을까요 ?**
지금은 virtual memory management가 발달되어 장기 스케줄러가 없기 때문에 스케줄러 종류를 따로 구분하지 않는다.

* **선점/비선점 스케줄링 방식의 차이점은 무엇인가요?**
이미 할당된 자원을 다른 프로세스가 강탈할수 있는지 없는지에 대해 차이가 있다. 비선점 스케줄링은 이미 진행중인 프로세스가 있으면 중간에 다른 프로세스를 할당할 수 없다. 반면 선점 스케줄링방식은 우선순위에 따라 진행중인 프로세스를 sleep시킨 후 더 높은 우선순위의 프로세스에 자원을 할당할 수 있다.

* **RR 알고리즘의 성능과 Time slice크기에는 어떤 연관성이 있을까요?**
알고리즘의 성능은 Time slice 크기와 같아진다. (waiting time관련)
Time slice 가 심하게 크다면 FCFS와 다를게 없다.
Time slice 가 너무 작다면 불필요한 Context Switch가 많이 일어난다.
따라서 좋은 성능을 내기 위해서는 적절한 Time slice가 필요하다.
