### ISSUE TITLE
10번째 : 네트워크 (TLS/SSL handshake, Load Balancing)

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#10]
# 일시  : 2022-02-14 오후 1시

# 주제 :

- TLS/SSL handshake

- 로드 밸런싱(Load Balancing)

**Comment by choiyoungkwon12** [comment]
## TLS / SSL Handshake 과정
1. client Hello: client에서 SSL버전 정보와 지원하는 암호화 방식, 무작위 바이트 문자열(이후에 사용하게 되는 중요한 데이터입니다)이 포함 되어 전달 됩니다. 이미 SSL handshake를 했었다면 세션을 재사용 할 수 있습니다.

2. server Hello: 지원하는 암호화 방식 중 서버에서 어떤것을 사용할 지, 세션 ID, 서버측에서 생성한 무작위 바이트 문자열을 전송합니다. 클라이언트에서 인증서를 요구하게 되면 SSL 인증서를 전송하게 됩니다.

3. 클라이언트는 인증서를 CA의 공개키로 복호화 한 후에 신뢰할 수 있는 사이트 인지 판단하게 됩니다.이 과정을 통해 클라이언트는 서버의 공개키를 얻게 됩니다.

  - 인증서가 서버가 신뢰할 수 있는지 어떻게 판단할까?

     - 서버는 CA의 비밀키로 암호화 된 SSL 인증서를 제공한다. 이 인증서에는 서버측의 공개키와 서비스의 정보를 담고있다.
     - 브라우저는 이 인증서를 발급한 CA가 자신의 CA리스트에 있는지 확인한다.
     - 있다면 CA의 해당 공개키를 이용해서 인증서를 복호화한다. 
     - 복호화가 된다면 이 인증서는 CA의 비공개키에 의해 암호화 되었다는 것을 알 수 있다.

4. 이후 클라이언트는 자신이 만든 무작위 바이트 문자열과 서버쪽에서 전송된 무작위 바이트 문자열을 조합하여 pre master secret키를 생성합니다. 이 키는 이후 데이터를 주고 받을 때 대칭키 방식을 사용할 때 사용하게 됩니다. 이 pre master secret키를 서버로 전송할 때 인증서에서 받았던 키를 이용하여 공개키 방식 암호화를 하게 됩니다. 그리고 서버쪽으로 전송하게 됩니다.

5. 서버쪽에서는 수신한 pre master secret키를 비밀키를 이용하여 복호화 하여 얻게된다.

6. server client 둘 다 일련의 과정을 거쳐 pre master secret키를 master key로 만들게 되고 이 master key를 이용하여 session key를 만들게 된다. 이후 데이터를 주고 받을 떄 session key를 대칭키 방식으로 이용하여 통신하게 됩니다.

7. 통신이 끝나면 세션키를 폐기합니다.

## 로드 밸런싱이란 무엇인가요??
   -  부하분산 또는 로드 밸런싱은 컴퓨터 네트워크 기술의 일종으로 중앙처리장치 혹은 저장장치와 같은 컴퓨터 자원들에게 작업을 효율적으로 나누는 것을 의미한다.

## 로드밸런서의 종류
  -  L4 , L7 이 가장 많이 활용됩니다.
  -  이유는 L4 로드밸런서부터 포트(Port)정보를 바탕으로 로드를 분산하는 것이 가능하기 때문입니다. 한 대의 서버에 각기 다른 포트 번호를 부여하여 다수의 서버 프로그램을 운영하는 경우라면 최소 L4 로드밸런서 이상을 사용해야만 합니다.

L4 : L4 로드밸런서는 네트워크 계층(IP, IPX)이나 트랜스포트 계층(TCP, UDP)의 정보를 바탕으로 로드를 분산합니다. IP주소나 포트번호, MAC주소, 전송 프로토콜에 따라 트래픽을 나누는 것이 가능합니다.

L7 : L7 로드밸런서의 경우 애플리케이션 계층(HTTP, FTP, SMTP)에서 로드를 분산하기 때문에 HTTP 헤더, 쿠키 등과 같은 사용자의 요청을 기준으로 특정 서버에 트래픽을 분산하는 것이 가능합니다.

**Comment by jerry0339** [comment]
### TSL (Transport Layer Security) 이란 ?
* SSL은 전자상거래 등의 보안을 위해 넷스케이프에서 처음 개발됨
* SSL이라는 명칭이 특정 회사의 제품 이름 같다하여 TLS로 표준화 됨
* TLS는 SSL 3.0을 기반으로 발표되었기 때문에, SSL과 거의 같다고 볼 수 있음
* 현재는 1999년에 처음 발표된 TLS 1.0이 계속 유지되어 오고 있음.
* SSL의 변화 : SSL 1.0 > SSL 2.0 > SSL3.0 > TLS1.0 > RFC 2246(표준규약)

<br>

### 로드 밸런싱(Load balancing)이란?
```
부하분산 또는 로드 밸런싱(load balancing)은 컴퓨터 네트워크 기술의 일종으로 
둘 혹은 셋이상의 중앙처리장치 혹은 저장장치와 같은 컴퓨터 자원들에게 작업을 나누는 것을 의미한다.

즉, 여러 서버가 작업을 분산 처리 하는것을 로드 밸런싱이라고 한다.
가용성 및 응답시간을 최적화 시킬 수 있다.
```
<br>

### AWS 로드 밸런서의 종류 ?
```
AWS 서비스를 사용하다보면 자주 접하게 되는 서비스가 로드 밸런싱이다.
AWS의 로드 밸런서(LB: Load balancer)는 OSI 7 계층 중 어느 계층에서 동작하는지에 따라 
NLB(Network LoadBalancer)와 ALB(Application LoadBalancer)로 나눌 수 있다. 
기존에는 CLB(Classic LoadBalancer)도 있었지만, 현재에는 거의 사용하지 않고 주로 NLB 또는 ALB를 사용하고 있다.
```

**Comment by Chaeonida** [comment]
# TLS/SSL이란?

인터넷은 안전한 통신을 위하여 암호화를 사용한다. 암호화란 일반적인 평문을 알아볼 수 없도록 암호화 하여 암호문으로 만드는 과정이다. 이와 같은 과정을 웹 브라우저와 웹 서버에는 HTTPS를 사용하여 암호화를 한다.

HTTPS는 SSL(Secure Socket Layer)/TLS(Transport Layer Security) 전송기술을 사용한다. TCP,UDP와 같은 일반적인 인터넷 통신에 안전한 계층을 추가하는 방식이다. 그리고 이 기술을 구현하기 위해 웹 서버에서 설치하는 것이 SSL/TLS dlswmdtjdlek. TLS는 SSL의 개선 버전으로, 최신 인증서는 TLS를 사용하지면 편의적으로 SSL인증서라고 부른다.

# 로드 밸런싱 알고리즘
✔ 라운드로빈
서버에 들어온 요청을 순서대로 돌아가며 배정하는 방식
서버와의 연결이 오래 지속되지 않는 경우 적합하다.

✔ 가중 라운드로빈 방식
각 서버에 가중치를 매기고 가중치가 높은 서버에 요청을 우선적으로 배정하는 방식
서버의 트래픽 처리 능력이 다른 경우 사용한다.

✔ 최소 연결 방식
요청이 들어온 시점에 가장 적은 연결 상태를 보이는 서버에 트래픽을 배정하는 방식.
서버에 분배된 트래픽들이 일정하지 않은 경우에 적합하다.

✔ IP 해시 방식
클라이언트의 IP주소를 특정 서버로 매핑하여 요청을 처리하는 방식
사용자가 항상 동일한 서버로 연결된다.
