### ISSUE TITLE
11번째 : 네트워크(Blocking,Non-blocking & Synchronous,Asynchronous , 웹 통신의 큰 흐름, DNS 라운드 로빈 방식)

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#11]
# 일시  : 2022-02-17(목) 오후 1시

# 주제 :

- Blocking,Non-blocking & Synchronous,Asynchronous

- Blocking & Non-Blocking I/O

- 웹 통신의 큰 흐름
[www.naver.com](http://www.naver.com/) 을 입력했을 때 일어나는 일

- DNS Round Robin 방식

**Comment by Chaeonida** [comment]
### 동기,비동기,블로킹,논블로킹 설명해주세요

 ✅블로킹 Blocking
A 함수가 B 함수를 호출 할 때, B 함수가 자신의 작업이 종료되기 전까지 A 함수에게 제어권을 돌려주지 않는 것

✅ 논블로킹 Non-blocking
A 함수가 B 함수를 호출 할 때, B 함수가 제어권을 바로 A 함수에게 넘겨주면서, A 함수가 다른 일을 할 수 있도록 하는 것.

✅ 동기 Synchronous
A 함수가 B 함수를 호출 할 때, B 함수의 결과를 A 함수가 처리하는 것.

✅ 비동기 Asynchronous
A 함수가 B 함수를 호출 할 때, B 함수의 결과를 B 함수가 처리하는 것. (callback)

### DNS란?
www.xxxx.com 과 같이 사람이 읽을 수 있는 이름을 192.0.0.1과 같은 숫자 IP주소로 변환하여 컴퓨터가 서로 통신 할 수 있도록 도와주는 서버이다. DNS 서버는 이름에 대한 요청을 IP주소로 변환하여 최종 사용자가 도메인 이름을 웹 브라우저에 입력할 때 해당 사용자를 어떤 서버에 연결할 것인지는 제어한다

### DNS ROUND ROBIN이란? 
별도의 SW,HW로드벨런싱 장비 없이 오직 DNS만을 이용하여 도메인 레코드 정보를 조회하는 시점에서 트래픽을 분산하는 기법이다.
웹 뿐만 아니라, 도메인을 사용하는 모든 서비스(FTP,SMTP 등)에 사용이 가능하다.

**Comment by jerry0339** [comment]
### 1. DNS Round Robin의 장단점 ?
* 장점
    * 중간 장비(로드밸런서) 없이도 서비스가 가능하다.
    * 비용이 저렴하다.
    * 간편하다.

* 단점
    * 서버에 장애 발생시 감지 및 원인을 찾기 힘들다.
    * 부하의 분산이 고르지 않다.
    * 서버에 이상이 있어도 부하를 분산시킨다.
    * DNS는 결과를 Caching하기 때문에 균등한 분산이 어렵다.
~~~
중간에 로드밸런서가 존재할 경우 일반적으로 트래픽을 담당하는 서버의 상태를 관찰(헬스 체크)하며 분산을 조절하지만
DNS Round Robin은 헬스체크가 없다. 또한 웹 서버에 문제가 생겨 서비스가 불가한 상태라도 DNS는 
이러한 문제를 감지할 수 없어 이상이 있어도 부하를 분산시킨다.
따라서 HA(High Availability)용도로 적합하지 않다.
~~~

<br>

### 2. Blocking,Non-blocking 그리고 Synchronous,Asynchronous의 차이점
#### Blocking과 Non-blocking
* **Block** : 행위자가 **막혀버린, 제한된, 대기하는 상태**
    ```
    <호출된 함수>가 자신이 할 일을 모두 마칠 때까지 제어권을 계속 가지고서 
    [호출한 함수]에게 바로 돌려주지 않으면 Block 
    즉, [호출한 함수]가 block
    ```
* **Non-block**
    ```
    <호출된 함수>가 자신이 할 일을 채 마치지 않았더라도 바로 제어권을 건네주어(return)
    [호출한 함수]가 다른 일을 진행할 수 있도록 해주면 Non-block
    ```

<br>

#### Synchronous와 Asynchronous
* **Synchronous** : 동시 발생하는 - (**always plural**, **can never be singular**)
    ```
    <호출된 함수>의 수행 결과 및 종료를 
    [호출한 함수]가(<호출된 함수>뿐 아니라 [호출한 함수]도 함께) 신경 쓰면 Synchronous
    즉, [호출한 함수]와 <호출된 함수>가 함께 작업완료를 신경씀
    ```

* **Asynchronous**
    ```
    <호출된 함수>의 수행 결과 및 종료를 
    <호출된 함수>가 혼자 직접 신경 쓰고 처리한다면(as a callback fn.) Asynchronous
    ```

**Comment by choiyoungkwon12** [comment]
❓ 동기 , 비동기, 블로킹, 논블로킹에 대해서 설명해주세요.

- 동기
동기 작업이란 작업을 수행하는 두 개 이상의 주체가 서로 동시에 수행하거나, 동시에 끝나거나, 끝나는 동시에 시작할 때를 의미합니다.

시작과 종료를 동시에 하거나, 하나의 작업이 끝나는 동시에 다른 주체가 작업을 시작하면 이는 동기 작업이라고 볼 수 있습니다.

- 비동기
비동기 작업은 두 주체가 서로의 시작, 종료시간과는 관계 없이 별도의 수행 시작/종료시간을 가지고 있을 때를 뜻합니다.

서로 다른 주체가 하는 작업이 자신의 작업 시작, 종료시간과는 관계가 없을 때 비동기라고 부를 수 있습니다.

- 블로킹
스레드 A가 어떤 작업을 하는 다른 대상을 호출하고, 그 대상이 가져온 결과물을 받아 다시 작업을 재개하고 있습니다. 예를 들자면 Java에서 JDBC를 사용하여 DB에 질의를 날리고 결과를 받아오는 작업을 블로킹 작업이라고 부를 수 있습니다.

- 논블로킹
이와 반대로 다른 주체에게 작업을 요청하고 그 결과를 받을 때까지 기다리지 않으며 자신의 작업을 한다면 이를 논블로킹이라고 할 수 있습니다.

❓ www.google.com을 브라우저에 입력했을 때 일어나는 일

1. 사용자가 브라우저에 도메인 이름을 입력한다.
2. DNS서버에서 사용자가 입력한 Domain name을 검색하고, 매핑되는 IP주소를 찾는다. 사용자가 입력한 URL 정보와 함께 리턴한다.
3. IP주소는 HTTP 프로토콜을 이용해서 HTTP 요청 메세지를 생성한다.
4. 생성된 HTTP 요청 메세지는 TCP 프로토콜을 사용해서 인터넷을 거쳐 해당 IP 주소의 컴퓨터(서버)로 전송된다.
5. 서버는 클라이언트의 요청을 승인하고, 응답 메세지를 전송한다.
6. 도착한 HTTP 응답 메세지는 HTTP 프로토콜을 사용하여 웹페이지 데이터로 변환되고, 웹 브라우저의 출력에 의해 사용자가 볼 수 있다.

❓ DNS 서버에서 IP 정보 수신하는 방법
DNS 서버에 DNS Query(www.example.com)를 전송한다

1. 우리나라의 경우에는 통신사별로 지정된 DNS 서버가 있다.
 - DNS 서버는 루트 네임 서버에 DNS Query를 질의한다.

2. 루트 네임 서버는 .com의 ip주소를 반환한다.
 - .com 네임 서버에 DNS 쿼리를 질의한다.

3. .com 네임 서버는 example.com의 ip주소를 반환한다.
 - example.com 네임 서버에 DNS 쿼리를 질의한다.

4. example.com 네임 서버에 DNS 쿼리를 질의한다.

 - www.example.com의 IP 주소를 반환한다.

**Comment by choiyoungkwon12** [comment]
👍
