### ISSUE TITLE
12번째 : 자료구조 (Array, List, HashTable)

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#12]
# 일시  : 2022-02-21 오후 4시

# 주제 :

- Array

- List

- HashTable

**Comment by Chaeonida** [comment]
###  Linked List(연결 리스트)의 장단점에 대해 설명해 주세요
✔ 장점
새로운 원소를 삽입/삭제하는데 시간이 빠르다.
연속적인 메모리 할당이 필요하지 않다.
✔ 단점
임의의 위치에 있는 원소를 확인하려면 첫 번째 원소부터 확인해야 하기 때문에 속도가 느리다.
이전 노드 및 다음 노드의 위치를 저장하기 위한 추가 메모리 공간이 필요하다.

###  배열을 언제 사용해야 좋은지 설명해주세요
데이터 개수가 확실하게 정해져 있을 때 데이터 저장을 위한 자료구조로 선택하면 좋다.
또한, 삽입/삭제 작업이 적을 때 사용하면 좋다.
마지막으로 배열에 저장된 데이터를 검색하는 작업이 많을 때 사용하면 좋다.(인덱스로 빠르게 검색 가능)

###  해시(Hash)값이 충돌하는 경우에 어떻게 해야하는지 설명해주세요
해시 테이블에서는 충돌에 의한 문제를 분리 연결법(Separate Chaining)과 개방 주소법(Open Addressing) 크게 2가지로 해결하고 있다.  분리 연결법은 동일한 버킷의 데이터에 대해 자료구조를 활용해 추가 메모리를 사용하여 다음 데이터의 주소를 저장하는 방법이고,  개방 주소법은 추가적인 메모리를 사용하는 분리연결 방식과 다르게 비어있는 해시 테이블의 공간을 활용하는 방법이다.

**Comment by choiyoungkwon12** [comment]
# ❓HashMap, HashTable, ConcurrentHashMap의 차이

|| 	Hashtable	|HashMap	|ConcurrentHashMap|
|---|---|---|---|
|thread-safe(synchronized)|	O|	X|	O|
|반환값	|Enumeration|	Fail-Fast Iterator|	Fail-Safe Iterator|
|성능 순위|	3|	1|	2|
|key, value에 null 허용|	X|	O|	X|
|사용할 상황|	X	|단일 스레드에서만 map을 사용하는 경우|	멀티 스레드 환경에서 map을 사용하는 경우|

MultiThread 환경에서 동기화 처리가 필요하다면 ConcurrentHashMap을 사용하는 것이 안정적이다. 동기화가 필요하지 않은 경우라면 그냥 HashMap을 사용하자. Hashtable은 Thread-Safe 하긴 하나 느리다는 단점이 있다.

---

# ❓hash 충돌이 일어난 경우 해결법

## 분리 연결법(Separating Chaining) 

- Separate Chaining이란 동일한 버킷의 데이터에 대해 자료구조를 활용해 추가 메모리를 사용하여 다음 데이터의 주소를 저장하는 것이다. 

- 위의 그림과 같이 동일한 버킷으로 접근을 한다면 데이터들을 연결을 해서 관리해주고 있다. 실제로 Java8의 Hash테이블은 Self-Balancing Binary Search Tree 자료구조를 사용해 만약 체이닝된 데이터가 8개이상이라면 트리를 사용하고 아니라면 리스트를 사용하여 Chaining 방식을 구현하였다.

## 개방 주소법(Open Addressing) 

Open Addressing이란 추가적인 메모리를 사용하는 Chaining 방식과 다르게 비어있는 해시 테이블의 공간을 활용하는 방법이다. Open Addressing을 구현하기 위한 대표적인 방법으로는 3가지 방식이 존재한다.

1. 선형 탐사(Linear Probing): 현재의 버킷 index로부터 고정폭 만큼씩 이동하여 차례대로 검색해 비어 있는 버킷에 데이터를 저장한다.

2. 제곱 탐사(Quadratic Probing): 해시의 저장순서 폭을 제곱으로 저장하는 방식이다. 예를 들어 처음 충돌이 발생한 경우에는 1만큼 이동하고 그 다음 계속 충돌이 발생하면 2^2, 3^2 칸씩 옮기는 방식이다.

3. 이중 해싱(Double Hashing Probing): 해시된 값을 한번 더 해싱하여 해시의 규칙성을 없애버리는 방식이다. 해시된 값을 한번 더 해싱하여 새로운 주소를 할당하기 때문에 다른 방법들보다 많은 연산을 하게 된다.

--- 

# ❓ArrayList와 LinkedList 시간 복잡도

|| 	ArrayList|	LinkedList|
|---|---|---|
|get / set	|O(1)	|O(n)|
|add(시작)	|O(n)	|O(1)|
|add(끝)	|O(1)	|O(1)|
|add(일반)	|O(n)	|O(n) (삽입 하는데에는 O(1)이지만 탐색하는 데 O(n)이 걸림|
|remove(시작)|	O(n)|	O(1)|
|remove(끝)	|O(1)	|O(1)|
|remove(일반)	|O(n)|	O(n) 삭제 하는데에는 O(1)이지만 탐색하는 데 O(n)이 걸림|

**Comment by jerry0339** [comment]
* **Array와 List의 차이점 ?**
리스트는 배열과 다르게 논리적 저장 순서와 물리적 저장 순서가 일치하지 않는다.
배열은 Compile time에 할당되는 정적 메모리 할당, 리스트는 새로운 Node가 추가되는 runtime에 할당되는 동적 메모리 할당
리스트는 순차적으로 접근하기 때문에 접근, 수정의 시간복잡도는 O(n) 배열은 O(1)
리스트의 삽입, 삭제는 O(1)이지만 해당 지점까지 접근해야하므로 O(n)일 수 있음

<br>

* **Open Addressing와 Separate Chaining 차이점 ?**
```
Open Addressing는 연속된 공간에 데이터를 저장하기 때문에 데이터 개수가 적으면
캐시적중률(cache hit ratio)이 높아 Separate Chaining보다 성능이 좋다. (데이터가 연속적으로 저장되어 있을 확률이 높기 때문)

하지만 배열의 크기가 커질수록 hit ratio도 낮아지고, 일정 개수 이상으로 데이터가 많아지면 일반적으로 Open Addressing은 Separate Chaining보다 느리다. 버킷을 채운 밀도가 높아질수록 Worst Case발생 빈도가 높아지기 때문이다.

하지만 Separate Chaining를 사용하면 Worst Case발생 빈도를 줄일 수 있도록 설계가 가능하기 때문에 데이터가 많아지면 Separate Chaining이 더 안정적이다. (예를들어 보조 해시 함수가 있다)

게다가 Open Addressing방식은 Linear구조상 데이터를 삭제할때 효율적이기 어렵기 때문에 Java의 HashMap에서는 Separate Chaining방식을 채택하여 사용중이다. (remove()메서드는 매우 빈번하게 호출될 수 있기 때문)
```

<br>

* **Java의 HashMap의 Tree 구현에서  레드-블랙 트리를 사용하는 이유 ?**

`레드-블랙 트리(Red-black tree)`는 자가 균형 이진 탐색 트리(self-balancing binary search tree)로서, 대표적으로는 연관 배열(associative array) 등을 구현하는 데 쓰이는 자료구조다. 레드-블랙 트리는 복잡한 자료구조지만, 실 사용에서 효율적이고, 최악의 경우에도 상당히 우수한 실행 시간을 보인다: 트리에 n개의 원소가 있을 때 O(log n)의 시간복잡도로 삽입, 삭제, 검색을 할 수 있다.

레드-블랙 트리는 자료의 삽입과 삭제, 검색에서 **최악의 경우에도 일정한 실행 시간을 보장**한다(worst-case guarantees). 이는 실시간 처리와 같은 실행시간이 중요한 경우에 유용하게 쓰일 뿐만 아니라, 일정한 실행 시간을 보장하는 또 다른 자료구조를 만드는 데에도 쓸모가 있다. 예를 들면, 각종 기하학 계산에 쓰이는 많은 자료 구조들이 레드-블랙 트리를 기반으로 만들어져 있다.
