### ISSUE TITLE
13번째 : 자료구조 (Queue,Heap,Stack) 

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#13]
# 일시  : 2022-02-25 오후 4시
# 주제 :

- Queue

- Heap

- Stack

**Comment by Chaeonida** [comment]
### 힙(Heap)에대해서 설명해주세요
힙 자료구조는 완전 이진 트리를 기초로 하는 자료구조입니다. 완전 이진트리는 마지막을 제외한 모든 노드에서 자식들이 꽉 채워진 이진트리를 말합니다.

**Comment by choiyoungkwon12** [comment]
## 스택에 대해서 설명해주세요.

- 한 쪽 끝에서만 자료를 넣고 뺄 수 있는 LIFO(Last In First Out) 형식의 자료 구조

각 연산에 대한 시간 복잡도

| 연산 | 시간복잡도 |
| --- | --- |
| Insertion | O(1) | 
| Deletion | O(1) | 
| Search | O(n) |

**Comment by jerry0339** [comment]
## 우선순위 큐(Priority Queue)에 대해서 설명해 주세요
큐에 우선순위의 개념이 들어간 자료구조이다. 각각의 데이터들이 우선순위를 가진다.

큐는 먼저 삽입된 데이터가 먼저 삭제 됐다면, 

우선순위 큐는 데이터 삽입시 우선순위에 따라 데이터가 정렬되며 

삭제시에는 **높은 우선순위를 가진 데이터**가 먼저 삭제 된다.

우선순위에 따른 정렬이 필요하기 때문에 큐나 스택처럼 선형(Linear) 자료구조를 이용하면 좋은 성능은 기대할 수 없다.

따라서 우선순위 큐의 데이터의 삽입과 삭제는 자료구조 **힙(Heap)**을 이용하여 구현할 수 있으며

데이터의 삽입과 삭제 모두 O(logN)의 시간복잡도를 가진다.
