### ISSUE TITLE
14번째 : 자료구조 (Graph, Tree, Trie)

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#14]
# 일시  : 2022-03-03 오후 4시

# 주제 :

- Graph

- Tree
   - Binary Tree
   - Full Binary Tree
   - Complete Binary Tree
   - Binary Search Tree

- Trie

**Comment by choiyoungkwon12** [comment]
#  그래프란 무엇인가요❓

- 그래프는 노드와 그 노드를 연결하는 간선을 하나로 모아 놓은 자료구조입니다.
- 종류는 무방향 그래프와 유방향 그래프, 가중치 그래프, 완전 그래프 등이 있습니다.
- 구현 방법은 인접행렬 방식과 인접리스트 방식이 있습니다.

# 트리가 무엇인가요❓

- 트리 (Tree)란 노드들이 나무 가지처럼 연결된 비선형 계층적 자료구조입니다.
- 트리는 또한 트리 내에 다른 하위 트리가 있고 그 하위 트리 안에는 또 다른 하위 트리가 있는 재귀적 자료구조이기도 합니다.
- 특징은 그래프의 한 종류이고 하나의 루트 노드와 0개 이상의 하위 트리로 구성되어 있습니다.

 # 이진 탐색 트리의 탐색 연산의 시간복잡도를 아시나요❓

- 이진 탐색 트리는 루트부터 비교해서 작으면 왼쪽으로 크면 오른쪽으로 이동하면서 탐색하면 되기 때문에 최대 트리의 높이만큼 비교할 수 있고 O(logN) 만큼의 시간복잡도를 가집니다.

**Comment by jerry0339** [comment]
## 그래프를 구현하는 방법 ?
#### 1. 인접 행렬
2차원 배열을 이용하여 간단하게 그래프를 구현할 수 있다.
구현이 쉽지만 인접 리스트에 비해 공간을 더 많이 차지하며 탐색에 더 많은 시간을 필요로 한다.


#### 2. 인접 리스트
위의 그래프를 인접 리스트로 표현한 그림이다.
인접 행렬보다 더 빠른 시간안에 탐색이 가능하며 공간도 더 적게 차지한다.

![image](https://user-images.githubusercontent.com/15929412/156530964-6895b1e1-ef2d-4580-9735-4f89983319b4.png)

<br> <br> 

## 유향 비순환 그래프란 ?
directed acyclic graph, 줄여서 DAG라고 함
관련 알고리즘으로 위상정렬이 있다.
(위상정렬은 방향 그래프의 정점들(vertex)을 변의 방향을 거스르지 않도록 나열하는 것을 의미함)
![image](https://user-images.githubusercontent.com/15929412/156531256-9cc49a4c-d20f-4c29-92c4-f85fc6bed59b.png)

<br><br>

## 이진 트리 순회 방법
- 중위 순회(In-order traversal): 왼쪽 자손, 자신, 오른쪽 자손 순서로 방문하는 순회 방법.
- 전위 순회(Pre-order traversal): 자신, 왼쪽 자손, 오른쪽 자손 순서로 방문하는 순회 방법.
- 후위 순회(Post-order traversal): 왼쪽 자손, 오른쪽 자손, 자신 순서로 방문하는 순회 방법.
- 너비 우선 순회(Breadth-First traversal)라고도 한다. 노드를 레벨 순서로 방문하는 순회 방법. 위의 세 가지 방법은 **스택**을 활용하여 구현할 수 있는 반면 레벨 순서 순회는 **큐**를 활용해 구현할 수 있다.

![image](https://user-images.githubusercontent.com/15929412/156531410-293810ad-408a-4264-9021-352b30314bb8.png)
위의 트리를 순회하면 다음과 같다.

- In-order: 1 3 4 6 7 8 10 13 14
- Pre-order: 8 3 1 6 4 7 10 14 13
- Post-order: 1 4 7 6 3 13 14 10 8
- Level-order(BFS): 8 3 10 1 6 14 4 7 13

**Comment by Chaeonida** [comment]
### 인접리스트의 장단점을 설명해주세요 
- 인접리스트 장점
1. 정점들의 연결 정보를 탐색할 때 O(n) 의 시간이면 가능합니다. (n: 간선의 갯수)
2. 필요한 만큼의 공간만 사용하기때문에 공간의 낭비가 적습니다.
- 인접리스트 단점
1. 특정 두 점이 연결되었는지 확인하려면 인접행렬에 비해 시간이 오래 걸립니다. (배열보다 search 속도느림)

### 트라이(Trie) 에대해 설명해 주세요
트라이(Trie)는 문자열을 저장하고 효율적으로 탐색하기 위한 트리 형태의 자료구조 입니다.

###  트리의 사용 사례는 어떤것이 있을까요? 
✔ 계층 적 데이터 저장
트리는 데이터를 계층 구조로 저장하는 데 사용됩니다.
예를 들어 파일 및 폴더는 계층적 트리 형태로 저장됩니다.

✔ 힙(Heap)
힙도 트리로 된 자료 구조입니다.

✔ 데이터 베이스 인덱싱
데이터베이스 인덱싱을 구현하는데 트리를 사용합니다.
예) B-Tree, B+Tree, AVL-Tree..

✔ Trie
사전을 저장하는 데 사용되는 특별한 종류의 트리입니다.
