### ISSUE TITLE
15번째 : 자료구조(정렬 알고리즘)

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#15]
# 일시  : 2022-03-07 오후 4시 이후

# 주제 :

정렬 알고리즘
 - 선택 정렬 
 - 거품 정렬
 -  삽입 정렬
 - 병합 정렬
 -  퀵 정렬
 -  힙 정렬

**Comment by Chaeonida** [comment]
### 버블정렬, 선택정렬 , 삽입정렬에 대해 설명해주세요 
- 버블 정렬
인접한 원소끼리 비교하여 교환하는 방식
셋 중에 제일 느리지만 단순함
- 선택 정렬
최솟값을 찾아서 맨 앞으로 이동하는 방식
버블 정렬보다 좋음
- 삽입 정렬
앞에서부터 차례대로 이미 정렬된 부분과 비교하여 교환하는 방식
셋 중에 제일 빠르지만 배열이 길어질수록 효율성이 떨어짐

모두 시간 복잡도는 O(n²)으로 
선택 정렬과 삽입 정렬은 사용할 메모리가 제한적인 경우에 사용하면 좋습니다.

**Comment by choiyoungkwon12** [comment]
## Arrays.sort() vs Collections.sort() 의 차이점은 ❓
  - Arrays.sort() 는 일단 기본 or 참조 타입 배열을 매개변수로 갖는 정렬 메서드입니다.
     - 내부적으로 기본 타입 배열인 경우는 dualPivotQuickSort를 사용하고 최악의 경우 NlogN를 보장하지 못합니다. 참조 타입인경우 TimSort를 사용하고 최악의경우에도 NlogN을 보장할 수 있습니다.
  - Collections.sort()는 컬렉션 타입을 정렬할 수 있는 메서드입니다.
     - 내부적으로 Arrays.sort를 사용하는데 참조타입 배열 형태로 사용해서 Timsort알고리즘을 사용합니다.

**Comment by sunH0** [comment]
퀵 정렬에서 **최악의 경우에**  피벗 값이 최소나 최대 값으로 지정되어 파티션이 나뉘어지지 않았을때, 즉 배열이 정렬되어 있으면 O(n^2)의 시간 복잡도를 갖는다.

## 퀵 정렬에서 최악의 경우를 방지하는 방법은??

1. 피벗이 항상 편향되는 최악의 경우를 막기 위해 피벗 값을 매범 랜덤한 위치에서 정한다.
2. 배열의 가장 첫 인덱스, 끝 인덱스, 중간 인덱스에 해당하는 값들을 정렬하고, 중간 값을 Pivot으로 사용
3. 삽입정렬과 함께 사용한다.  만약 arr의 size가 특정 수 (e.g. 200) 이하라면 삽입정렬, 그 것보다 크면 퀵정렬을 사용하여 정렬
