### ISSUE TITLE
17번쩨 : 데이터베이스 (데이터베이스, 인덱스, Sharding&Master/Slave)

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#17]
# 일시  : 2022-03-14 오후 4시

# 주제 :

- 데이터베이스
   - 데이터베이스를 사용하는 이유
   - 데이터베이스 성능
- Sharding&Master/Slave(2)
- Index
   - Index 란 무엇인가
   - Index 의 자료구조
   - Primary index vs Secondary index
   - Composite index
   - Index 의 성능과 고려해야할 사항
   - Clustered index, Non-Clustered index

**Comment by choiyoungkwon12** [comment]
# 마스터 - 슬레이브 구조를 사용한 경험이나 알고 있는지?

- 사용한 경험은 없고 여러 노드에 데이터를 복제하여 사용하는 방법이다.

- 이 때 노드를 마스터 노드와 슬레이브 노드라고 부르며, 모든 쓰기는 마스터에서 행하고 읽기는 마스터나 슬레이브에서 처리 된다. 쓰기가 실행 될 경우, 데이터는 마스터에서 슬레이브로 복제된다.

- 읽기를 마스터 노드와 슬레이브 노드에서 처리하므로, 읽기가 많이 발생하는 작업에서 성능 효과를 얻게 된다. (더 많은 읽기 요청을 처리하고 싶다면 스케일 업을 하면 된다.)

- 만약 마스터 노드가 문제가 생기면 다른 슬레이브 노드가 마스터 노드가 되는 방식을 사용할 수도 있다. 이럴 경우 쓰기 작업(마스터가 실행하는)이 실패해도 빠르게 복구 가능하다.

# 샤딩을 알고 있는지? 언제 사용할 수 있는지

- 샤딩(sharding)은 horizontal partitioning(수평적)과 관련된 데이터베이스 설계 패턴이다.
- 한 테이블의 row들을 여러 개의 서로 다른 테이블, 즉 파티션으로 분리하는 것을 말한다.
- 여러 복잡성 때문에, sharding은 대규모의 데이터를 다룰 때 주로 사용된다.

## 고려 해야 할 상황은

- 애플리케이션 데이터의 양이 단일 database node의 스토리지 한계를 초과했을 때
- 쓰기 & 읽기 양이 단일 노드나 read replica가 핸들링할 수 있는 수준을 넘어서서 반응이 느려졌을 때
- 하나의 database node 또는 read replica에 가능한 네트워크 대역폭을 초과해 반응 속도가 느려졌을 때

사용할 수 있을 것 같습니다.

# 인덱스가 무엇인지 아는지? 사용한 경험이 있는지?

- 인덱스는 데이터베이스 테이블에 대한 검색 성능의 속도를 높여주는 자료 구조입니다.

- 만약 우리가 책에서 원하는 내용을 찾는다고 하면, 책의 모든 페이지를 찾아 보는것은 오랜 시간이 걸린다. 그렇기 때문에 책의 저자들은 책의 맨 앞 또는 맨 뒤에 색인을 추가하는데, 데이터베이스의 index는 책의 색인과 같다.

- 데이터베이스에서도 테이블의 모든 데이터를 검색하면 시간이 오래 걸리기 때문에 데이터와 데이터의 위치를 포함한 자료구조를 생성하여 빠르게 조회할 수 있도록 돕고 있다.

- 인덱스를 활용하면, 데이터를 조회하는 SELECT 외에도 UPDATE나 DELETE의 성능이 함께 향상된다. 그러한 이유는 해당 연산을 수행하려면 해당 대상을 조회해야만 작업을 할 수 있기 때문이다.

사용 경험은 따로 인덱스를 구성해서 사용한 경험은 없지만, 기본키가 기본적으로 index가 되는 거로 알고 있고 기본키를 가지고 검색한 경험은 있습니다.

**Comment by jerry0339** [comment]
## 데이터의 중복성으로 일어날 수 있는 문제들 ?
* '데이터 중복성' 문제는 데이터 일관성, 데이터 보안성, 경제성, 데이터 무결성과 같은 문제들을 야기한다.

**데이터 일관성(Data Consistency)** 
```
동일한 데이터가 여러 파일들로 존재하게 되었을 때, 그 내용은 모두 일관되게 동일하여야 한다. 
하지만 중복으로 존재할 경우 하나의 파일로 존재하는 경우보다 이 동일성을 유지하기 어렵게 된다. 
결과적으로 하나의 시스템 내에서 데이터의 일관성이 깨지게 되는 것이다. (data inconsistency)
```

<br>

**데이터 보안성(Data Security)** 
```
중복된 데이터에 대해서 동일한 수준의 데이터 보안이 적용되어야 하지만 
데이터가 중복된 상황에서 같은 수준의 보안을 유지하는 것은 어려울 수 있다.
```

<br>

**경제성(Economics)**
```
데이터를 중복으로 저장하는 것은 필요로하는 저장 공간에 대한 비용이 늘어나는 것을 의미하므로 
하나의 파일로만 저장하는 것과 비교하여 당연히 저장 비용의 증가로 이어질 수 있다. 
또한 일관성 유지를 위해 갱신 작업은 모든 중복된 데이터를 찾아 갱신하는 것을 의미하므로 
이 또한 비용의 증가로 이어질 수 있다.
```

<br>

**데이터 무결성(Data Integrity)**
```
데이터 중복은 자연스럽게 제어의 분산으로 이어질 수 있다.
이에 따라 데이터 무결성(데이터 정확성)을 유지하기 어려워질 수 있다.
```

<br> <br> 

## 인덱스의 장점과 단점 ?
**장점**
1. 테이블을 조회하는 속도와 그에 따른 성능을 향상시킬 수 있다.
2. 전반적인 시스템의 부하를 줄일 수 있다.

<br>

**단점**
1. 인덱스를 관리하기 위해 DB의 약 10%에 해당하는 저장공간이 필요하다.
2. 인덱스를 관리하기 위해 추가 작업이 필요하다.
3. 인덱스를 잘못 사용할 경우 오히려 성능이 저하되는 역효과가 발생할 수 있다.
    ```
    만약 CREATE, DELETE, UPDATE가 빈번한 속성에 인덱스를 걸게 되면 인덱스의 크기가 비대해져서 성능이 오히려 저하되는 역효과가 발생할 수 있다. 
    그러한 이유 중 하나는 DELETE와 UPDATE 연산 때문이다. 
    앞에서 설명한대로, UPDATE와 DELETE는 기존의 인덱스를 삭제하지 않고 '사용하지 않음' 처리를 해준다고 하였다. 
    만약 어떤 테이블에 UPDATE와 DELETE가 빈번하게 발생된다면 실제 데이터는 10만건이지만 인덱스는 100만 건이 넘어가게 되어, 
    SQL문 처리 시 비대해진 인덱스에 의해 오히려 성능이 떨어지게 될 것이다. 
    ```
<br> <br>

## 일반적으로 인덱스를 구현하는데 해시테이블을 사용하지 않는 이유 ?
```
해시 테이블은 (Key, Value)로 데이터를 저장하는 자료구조 중 하나로 빠른 데이터 검색이 필요할 때 유용하다. 
해시 테이블은 Key값을 이용해 고유한 index를 생성하여 그 index에 저장된 값을 꺼내오는 구조이다.
하지만 DB 인덱스에서 해시 테이블이 사용되는 경우는 제한적인데, 
그러한 이유는 해시가 등호(=) 연산에만 특화되었기 때문이다. 
해시 함수는 값이 1이라도 달라지면 완전히 다른 해시 값을 생성하는데, 
이러한 특성에 의해 부등호 연산(>, <)이 자주 사용되는 데이터베이스 검색을 위해서는 해시 테이블이 적합하지 않다.
```

**Comment by Chaeonida** [comment]
### 데이터베이스의 특징
✔ 데이터의 독립성
물리적 독립성 : 데이터베이스 사이즈를 늘리거나 성능 향상을 위해 데이터 파일을 늘리거나 새롭게 추가하더라도 관련된 응용 프로그램을 수정할 필요가 없다.
논리적 독립성 : 데이터베이스는 논리적인 구조로 다양한 응용 프로그램의 논리적 요구를 만족시켜줄 수 있다.

✔ 데이터의 무결성
여러 경로를 통해 잘못된 데이터가 발생하는 경우의 수를 방지하는 기능으로 데이터의 유효성 검사를 통해 데이터의 무결성을 구현하게 된다.

✔ 데이터의 보안성
인가된 사용자들만 데이터베이스나 데이터베이스 내의 자원에 접근할 수 있도록 계정 관리 또는 접근 권한을 설정함으로써 모든 데이터에 보안을 구현할 수 있다.

✔ 데이터의 일관성
연관된 정보를 논리적인 구조로 관리함으로써 어떤 하나의 데이터만 변경했을 경우 발생할 수 있는 데이터의 불일치성을 배제할 수 있다. 또한 작업 중 일부 데이터만 변경되어 나머지 데이터와 일치하지 않는 경우의 수를 배제할 수 있다.

✔ 데이터 중복 최소화
데이터베이스는 데이터를 통합해서 관리함으로써 파일 시스템의 단점 중 하나인 자료의 중복과 데이터의 중복성 문제를 해결할 수 있다.

### B-tree와 B+tree 에대해 설명해주세요

B+tree는 B-tree의 확장개념으로, B-tree의 경우, internal 또는 branch 노드에 key와 data를 담을 수 있습니다.
하지만, B+tree의 경우 브랜치 노드에 key만 담아두고, data는 담지 않습니다. 오직 리프 노드에만 key와 data를 저장하고, 리프 노드끼리 Linked list로 연결되어 있습니다. 풀 스캔 시, B+tree는 리프 노드에 데이터가 모두 있기 때문에 한 번의 선형탐색만 하면 되기 때문에 B-tree에 비해 빠릅니다. B-tree의 경우에는 모든 노드를 확인해야 합니다.

### Index 의 성능과 고려해야할 사항

SELECT 쿼리의 성능을 월등히 향상시키는 INDEX 항상 좋은 것은 아니다. 우선, 첫번째 이유는 INDEX 를 생성하게 되면 INSERT, DELETE, UPDATE 쿼리문을 실행할 때 별도의 과정이 추가적으로 발생한다. INSERT 의 경우 INDEX 에 대한 데이터도 추가해야 하므로 그만큼 성능에 손실이 따른다. DELETE 의 경우 INDEX 에 존재하는 값은 삭제하지 않고 사용 안한다는 표시로 남게 된다.

두번째로 데이터의 형식에 따라 인덱스를 만들면 효율적이고 만들면 비효율적은 데이터의 형식이 존재한다. 이름, 나이, 성별 세 가지의 필드를 갖고 있는 테이블을 생각해보면 이름은 온갖 경우의 수가 존재할 것이며 나이는 INT 타입을 갖을 것이고, 성별은 남, 녀 두 가지 경우에 대해서만 데이터가 존재할 것임을 쉽게 예측할 수 있다. 이 경우 이름에 대해서만 인덱스를 생성하면 효율적이다.

**Comment by sunH0** [comment]
## 인덱스  컬럼 기준은 어떻게 설정하나요?
카디널리티를 고려해야 합니다. 카디널리티란 해당 컬럼 값의 중복된 수치를 말합니다. 중복된 수치가 낮을 수록 인덱스를 통해 많은 레코드를 걸러내어 빠르게 조회할 수 있습니다. 또한 여러 컬럼을 인덱스로 설정해야 하는 경우 카디널리티가 높은 순에서 낮은 순으로 구성하는게 성능이 더 뛰어납니다.

## 인덱스의 키 값의 크기가 성능에 영향이 있나요?
mysql 의 기준으로  페이지 크기는 16KB로 설정되어 있습니다. 인덱스 키 값이 커지면 페이지당 저장할 수 있는 데이터 수가 감소하여 여러개의 페이지를 읽어야합니다. 또한,  InnoDB가 액세스 할 때 테이블 및 인덱스 데이터를 캐시하는 메인 메모리 영역인 innodb buffer pool에 저장되는 수도 감소하여 캐시 효율성도 떨어집니다.

### Replication 사용 목적
- 스케일 아웃
  - 갑자기 늘어나는 트래픽을 대응하는데 유연한 구조
- 데이터 백업
  - 레플리카를 하지 않더라도 데이터를 백업해야한다
  - 백업 과정은 실제 처리중인 쿼리에 영향을 미칠 수 있다
  - 레플리카 서버에서 데이터를 백업하여 소스 서버에서 백업시 발생하는 문제를 해결할 수 있다
- 데이터 분석
  - 분석용 쿼리는 대량의 데이터를 조회하고 쿼리 자체가 무거운 경우가 많다
  - 레플리카 서버에서 분석용 쿼리만 적용하는 것이 좋다
- 데이터의 지리적 분산
  - 데이터베이스와 애플리케이션 서버가 멀리 떨어져 있다면 응답을 늦게 받게 된다
  - 빠른 응답을 위해서 애플리케이션 서버에 가깝게 서버를 구성하는 것이 좋다
  - 자연 재해와 같은 이유로 데이터베이스 서버 중 하나가 파괴되어도 데이터는 보존된다
- 쿼리 병렬 처리
  - 데이터 변경은 소스 서버에서 이루어지고, 읽기 연산은 레플리카에 분산되어 병렬로 처리할 수 있는 쿼리가 늘어난다
