### ISSUE TITLE
18번쩨 : 데이터베이스 (정규화, statement)

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#18]
# 일시  : 2022-03-17 오후 4시

# 주제 :

정규화
 - 정규화에 대해서
 - 정규화 탄생 배경
 - 정규화란 무엇인가
 - 정규화의 종류
 - 정규화의 장단점

Statement vs PreparedStatement

**Comment by Chaeonida** [comment]
### 정규화를 하는 이유는 무엇인가요? 
한 릴레이션에 여러 엔티티의 애트리뷰트들을 혼합하게 되면 정보가 중복 저장되며, 저장 공간을 낭비하게 된다. 또 중복된 정보로 인해 갱신 이상이 발생하게 된다. 동일한 정보를 한 릴레이션에는 변경하고, 나머지 릴레이션에서는 변경하지 않은 경우 어느 것이 정확한지 알 수 없게 되는 것이다. 이러한 문제를 해결하기 위해 정규화 과정을 거치는 것이다.

### BCNF 정규화에대해 설명해주세요
BCNF 정규화란 제3 정규화를 진행한 테이블에 대해 모든 결정자가 후보키가 되도록 테이블을 분해하는 것이다.

### 반정규화에 대해 설명해주세요
반정규화(De-normalization)는 시스템의 성능 향상을 위해 정규화된 데이터 모델을 통합하는 작업으로, 의도적으로 정규화 원칙을 위배하는 행위이다. 사용되는 테이블에 액세스하는 프로세스의 수가 가장 많고, 항상 일정한 범위만을 조회하는 경우, 테이블에 대량 데이터가 있고 대량의 범위를 자주 처리하는 경우, 성능 상 이슈가 있을 경우, 테이블에 지나치게 조인을 많이 사용하게 되어 데이터를 조회하는 것이 기술적으로 어려울 경우에  반정규화를 진행한다.

**Comment by jerry0339** [comment]
### 정규화가 생겨난 배경 ?

한 릴레이션(Relation)에 여러 엔티티의 속성을 혼합하면 정보가 중복 저장되며 저장 공간을 낭비하게 된다.

또 중복된 정보로 인해 **이상 현상**이 발생하게 된다. 이러한 문제를 해결하기 위해 정규화 과정을 거치는 것이다. 

<br> <br>

### 이상현상 이란 ?
* 테이블 내의 데이터들이 불필요하게 **중복**되어 테이블을 조작할 때 발생되는 **데이터 불일치 현상**

1. 삽입 이상 (insertion anomaly) : 어떠한 특정 사실은 전혀 기록되지 않는 경우가 발생
2. 삭제 이상 (deletion anomaly) : 데이터의 삭제가 전혀 다른 사실에 대한 데이터의 삭제도 필요로 하게 되는 현상
3. 갱신 이상 (update anomaly) : 같은 정보가 복수개의 행에서 표현되어서 갱신은 논리적인 모순을 낳게 된다.

<br> <br>

### BCNF 정규형이란 ?
BCNF 정규형은 3.5 정규형이라고도 하며 아래와 같은 필요조건이 있다.
* 3NF의 모든 요구 사항을 충족
* 후보 키가 다른 속성에 부분적으로 의존하지 않는 경우 모든 테이블은 BCNF에 있다고 한다. 
    (x, y, z) 열이있는 모든 테이블에서 (x, y)-> z 및 z-> x이면 BCNF 위반이다. 
    (x, y)가 복합 키이고 (x, y)-> z이면 직접 또는 부분적으로 역 종속성이 없어야한다.

예를들어 아래의 테이블은 3NF를 만족하지만 BCNF를 만족하지 못한다.

<br>

* **학생의 수강 신청**
    | Student | Course | Professor |
    |:----:|:-------:|:----:|
    | Chip Masterson | Machine Learning | Andrew Ng |
    | Al Fredrickson | Java Programming | James Gosling |
    | Al Fredrickson | Machine Learning | Andrew Ng |
    | Bob Albertson | Java Programming | James Gosling |
    | Chip Masterson | Algorithm | Dijkstra |

{Student, Course} 를 기본키로 선정한 경우 3NF 까지 만족하지만 삽입이상, 갱신이상, 삭제이상이 생길 수 있다.

* 삽입이상
    Algorithms 라는 수업이 Dijkstra 에 의해 열렸다고 하자. 하지만 수강생이 아무도 없는 경우 삽입할 수 없다.
* 갱신이상
    James Gosling 이 담당하는 강의가 바뀌게 될 경우 수강생의 수만큼 갱신해줘야 하므로
    하나라도 빠뜨리면 데이터 불일치 문제가 발생할 여지가 있다.
* 삭제이상
    Bob Albertson이 Java Programming수업을 수강취소하여 수강생이 없어지면 James Gosling 이라는 교수도 사라진다.

**Comment by choiyoungkwon12** [comment]
## 정규화, 반정규화 사례가 있으신가요??
   - 기본적으로 프로젝트 할 때 erd을 구성할 때 정규화를 하도록 테이블를 최대한 나눴습니다.
   - 그중에서 조인이 많이 일어나면서 조회가 많이 일어나는 경우 (선물 받기)에 해당하는 컬럼에 대해서 반정규화를 진행했습니다.
## 정규화 장단점
   -  db 이상현상을 제거
   - 저장 공간의 최소화 가능
   - 데이터 구조의 안정성 및 무결성 유지
   
단점으로는 
- 릴레이션 간의 join 연산 증가
   -  이로 인한 질의에 대한 응답 시간 저하
## statement vs preparedstatedment 차이점
   -  가장 큰 차이점은 캐시 여부인것 같습니다.
   - statement는 캐시하지 않고 인라인 값이 있는 쿼리를 db에 전달합니다.
   - preparedstatement는 사전 컴파일을 사용하고 컴파일 전에 캐시를 확인합니다.

**Comment by sunH0** [comment]
## 정규화가 왜 필요하나요?
데이터 베이스를 잘못 설계하면 불필요한 데이터가 중복되고 데이터를 삽입, 갱신, 삭제하는 과정에서 이상 상태가 발생할 수 있습니다. 이러한 문제를 해결하기 위해 정규화를 사용합니다. 다만, 릴레이션의 분해로 인해 join 연산이 많아져서 질의에 대한 응답 시간이 느려질 수 있습니다.

## 정규화 장단점

#### 장점
데이터베이스의 이상 현상을 막을 수 있다. : 일관성
정규화된 데이터베이스 구조에서 새로운 데이터 형의 추가로인한 확장 시, 그 구조를 변경하지 않아도 되거나 일부만 변경해도된다.
중복 제거
정규화된 테이블의 관계는 현실 세계의 개념들과 관계를 반영한다. (사용자에게 데이터 모델을 더욱 의미있게 제공)

#### 단점
릴레이션 분해로 많은 조인 연상이 발생할 수 있다. 이를 해결하기 위해서 반정규화를 진행하는 방법이 있다.

## 반정규화를 하는 이유가 있나요??
반정규화는 시스템의 성능 향상 및 개발과 운영의 단순화를 위해  정규화된 데이터 모델을 통합, 중복, 분리하는 데이터 모델링 기법입니다. 

반정규화는 다음 의 경우에 대상이 될 수 있습니다.

- 테이블의 조인(JOIN)연산을 지나치게 잦아서 데이터를 조회의 성능이 안 좋을 경우
- 테이블에 많은 데이터가 있고, 다량의 범위 혹은 특정 범위를 자주 처리해야 하는 경우

반정규화를 한다면 다음의 장점이 있습니다.

- 테이블이 단순해지고 관리 효율성이 증가
- 검색 기능은 향상되지만, 갱신, 삭제 등의 성능은 낮아진다.
- 데이터의 중복 방지, 무결성 vs 데이터베이스의 성능, 단순화 사이의 우선순위를 잘 조절하여 정규화/반정규화를 수행해야 한다
