### ISSUE TITLE
19번째 : 데이터베이스(트랜잭션)

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#19]
# 일시  : 2022-03-21 오후 4시

# 주제 :
Transaction
 - 트랜잭션(Transaction)이란 무엇인가?
 - 트랜잭션과 Lock
 - 트랜잭션의 특성
 - 트랜잭션의 상태
 - 트랜잭션을 사용할 때 주의할 점
 - 트랜잭션 격리수준
 - ACID
 - 교착상태

**Comment by Chaeonida** [comment]
###  트랜잭션의 성질에 대해 설명해주세요
✔ Atomicity(원자성)
- 트랜잭션의 연산은 데이터베이스에 모두 반영되든지 아니면 전혀 반영되지 않아야 한다.

- 트랜잭션 내의 모든 명령은 반드시 완벽히 수행되어야 하며, 모두가 완벽히 수행되지 않고 어느하나라도 오류가 발생하면 트랜잭션 전부가 취소되어야 한다.

✔ Consistency(일관성)
- 트랜잭션이 그 실행을 성공적으로 완료하면 언제나 일관성 있는 데이터베이스 상태로 변환한다.

- 시스템이 가지고 있는 고정요소는 트랜잭션 수행 전과 트랜잭션 수행 완료 후의 상태가 같아야 한다.

✔ Isolation(독립성,격리성)
둘 이상의 트랜잭션이 동시에 병행 실행되는 경우 어느 하나의 트랜잭션 실행중에 다른 트랜잭션의 연산이 끼어들 수 없다.

수행중인 트랜잭션은 완전히 완료될 때까지 다른 트랜잭션에서 수행 결과를 참조할 수 없다.

### Transaction 관리를 위한 DBMS의 전략에 대해 설명해주세요 
UNDO 와 REDO 두가지로 나뉘고
undo는 Buffer 교체는 transaction과는 무관하게 buffer의 상태에 따라서 결정됨. 이로 인해, 정상적으로 종료되지 않은 transaction이 변경한 page들은 원상 복구 되어야 하는것을 의미한다. 
redo는 이미 commit한 transaction의 수정을 재반영하는 복구 작업

✔ Durablility(영속성,지속성)
성공적으로 완료된 트랜잭션의 결과는 시스템이 고장나더라도 영구적으로 반영되어야 한다.

### 데드락의 발생조건에 대해 설명해주세요 
✔ 상호 배제
한 번에 프로세스 하나만 해당 자원을 사용할 수 있다. 사용 중인 자원을 다른 프로세스가 사용하려면 요청한 자원이 해제될 때까지 기다려야 한다.

✔ 점유 대기
자원을 최소한 하나 보유하고, 다른 프로세스에 할당된 자원을 점유하기 위해 대기하는 프로세스가 존재해야 한다.

✔ 비선점
이미 할당된 자원을 강제로 빼앗을 수 없다(비선점).

✔ 순환 대기
대기 프로세스의 집합이 순환 형태로 자원을 대기하고 있어야 한다.

**Comment by choiyoungkwon12** [comment]
# 트랜잭션이 무엇인가요?
트랜잭션(Transaction)은 데이터베이스에서의 논리적 작업 단위이다.

하나의 작업을 수행하기 위해 필요한 데이터베이스 연산 기능들을 모아놓은 것이며 분리되지 않도록 하여 작업의 완전성을 보장한다.

트랜잭션을 통해서 데이터베이스의 회복과 병행 제어가 가능하다. 즉, 데이터베이스에서 오류가 발생하는 경우의 빠른 회복이나, 여러 사용자가 동시에 데이터베이스를 사용할 수 있도록 제어해주는 중요한 역할을 한다.

데이터베이스의 연산을 SQL문으로 표현한다면, 하나의 작업을 수행하는 SQL문의 집합으로 생각할 수도 있다.

# 트랜잭션 격리 수준에 대해서 아시나요?
트랜잭션 격리수준(isolation level)이란 동시에 여러 트랜잭션이 처리될 때, 트랜잭션끼리 얼마나 서로 고립되어 있는지를 나타내는 것이다.

간단하게 말해 특정 트랜잭션이 다른 트랜잭션에 변경한 데이터를 볼 수 있도록 허용할지 말지를 결정하는 것이다.

격리수준은 크게 아래의 4개로 나뉜다.
- READ UNCOMMITTED
- READ COMMITTED
- REPEATABLE READ
- SERIALIZABLE

스프링에서 @Transactional의 옵션 값으로 격리수준을 정할 수 있는데 기본 값으로는 사용하는 DB의 default 값을 따른다.

# db 충돌 개선 전략을 아시나요?
database에 접근해서 데이터를 수정할 때 동시에 수정이 일어나 충돌이 일어날 수 있습니다. 우리는 이런 상황을 해결할 수 있도록 코딩을 진행해야합니다. 어떻게 해결할 수 있을까요 ?

첫번째, 테이블의 row에 접근시 Lock을 걸고 다른 Lock이 걸려 있지 않을 경우에만 수정을 가능하게 할 수 있습니다.

두번째, 수정할 때 내가 먼저 이 값을 수정했다고 명시하여 다른 사람이 동일한 조건으로 값을 수정할 수 없게 하는 것입니다.

## 비관적 락(pessimistic lock)

트랜잭션에서 변경하려는 레코드에 대해 락을 획득하고 쿼리를 수행하는 방식 (같은 레코드를 변경하려는 경우가 많을 것이라고 비관적인 생각을 하기 때문에 비관적 락)

비관적 락이란 트랜잭션이 시작될 때 Shared Lock 또는 Exclusive Lock을 걸고 시작하는 방법입니다.

즉, Shared Lock을 걸게 되면 write를 하기위해서는 Exclucive Lock을 얻어야하는데 Shared Lock이 다른 트랜잭션에 의해서 걸려 있으면 해당 Lock을 얻지 못해서 업데이트를 할 수 없습니다.

수정을 하기 위해서는 해당 트랜잭션을 제외한 모든 트랜잭션이 종료(commit) 되어야합니다.

![image](https://user-images.githubusercontent.com/47075043/159884770-c7747f73-9878-4172-90f6-70378baa3074.png)

## 낙관적 락(optimistic lock)

트랜잭션에서 락 없이 일단 쿼리 수행을 하고 마칠 때 서로 다른 트랜잭션에서 충돌이 있었는지 확인하고 문제가 있으면 충돌이 난 트랜잭션을 롤백하는 방식 (같은 레코드를 변경하려는 경우가 거의 없을 것이라고 낙관적인 생각을 하기 때문에 낙관적 락)

이 특징은 DB에서 제공해주는 특징을 이용하는 것이 아닌 Application Level에서 잡아주는 Lock입니다.

![image](https://user-images.githubusercontent.com/47075043/159884828-5473e1b4-0dce-49fb-ab31-b382851c4747.png)
