### ISSUE TITLE
1번째 : 프로세스와 스레드

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#2]
일시 : 2022-01-10 (월) 

# 이번 주제
프로세스와 스레드

**Comment by Chaeonida** [comment]
1. 스택을 스레드마다 독립적으로 할당하는 이유?
스택은 함수 호출 시 전달되는 인자, 되돌아갈 주소값 및 함수 내에서 선언하는 변수 등을 저장하기 위해 사용되는 메모리 공간이므로 스택 메모리 공간이 독립적이라는 것은 독립적인 함수 호출이 가능하다는 것이고 이는 독립적인 실행 흐름이 추가되는 것이다. 따라서 스레드의 정의에 따라 독립적인 실행 흐름을 추가하기 위한 최소 조건으로 독립된 스택을 할당한다.

2. PC Register 를 스레드마다 독립적으로 할당하는 이유?
PC 값은 스레드가 명령어의 어디까지 수행하였는지를 나타나게 된다. 스레드는 CPU 를 할당받았다가 스케줄러에 의해 다시 선점당한다. 그렇기 때문에 명령어가 연속적으로 수행되지 못하고 어느 부분까지 수행했는지 기억할 필요가 있다. 따라서 PC 레지스터를 독립적으로 할당한다.

**Comment by choiyoungkwon12** [comment]
## 프로세스와 스레드에 대해서 설명해주세요
  - 스레드 : 프로세스 내에서 실행되는 작업 흐름의 단위
  - 프로세스 : 프로세서에 의해 동작하고 있는 프로그램
    - 프로세스가 동작한다는 것은 프로세스의 특정 스레드가 실행 중
    - 그 특정 스레드는 프로세스가 가진 데이터를 참조함.

## 메모리 크기를 초과하는 프로세스가 실행되고 있으면 어떻게 되는가?

- 프로세스가 많이 실행되고 있는 경우 메모리의 크기를 넘어가게 될 수 있다. 이때 사용 되는 것이 ‘페이징’이다.

- 원래 메모리에 올라와 있어야할 데이터를 디스크에 저장하는 것이다. 
- 페이징 이라는 말 그대로 원래는 메모리 위에 올라와 있어야할 데이터를 ‘페이지’처럼 잘라서 일부는 메모리 위에, 일부는 디스크에 저장했다가 필요할 때 불러오는 방식이다. ‘어떤 페이지를 메모리에 올려 두느냐’가 중요한데 메모리에 원하는 페이지가 없으면 디스크에서 읽어 오는 만큼의 시간이 지연되기 때문이다.

- 페이징이 하나의 프로세스를 쪼개는 거라면, 여러 프로세스 중 어떤 프로세스를 메모리에 올려둘 것인지 선택하는 것도 필요하다. 
- 이를 선택하는 것을 ‘장기 스케줄링(Long-Term Scheduling)’이라고 한다. 그럼 ‘단기 스케줄링(Short-Term Scheduling)’도 있지 않겠는가? 단기 스케줄링은 바로 메모리에 올라와 있는 프로세스 중 어떤 프로세스를 CPU가 실행시킬지 결정하는 것을 말한다.

## 메모리 없이 CPU에서 바로 디스크로 접근하면 안되나?

- 그런 구조의 컴퓨터를 만든다면 가능하다.
하지만 일반적으로 컴퓨터가 디스크 > 메모리 > CPU 의 구조를 가진 것은 다분히 경제적인 이유가 숨어있다. 디스크는 용량이 크지만, 속도가 느리다. 메모리는 용량이 좀 더 작지만 속도는 디스크보다 월등히 빠르다. CPU는 뭔가 저장하기 위한 장치가 아니기 때문에 용량이라고 할 것도 없지만, 속도는 디스크와는 비교도 안될 만큼 빠르고 메모리 보다도 월등히 빠르다. 그럼 여기서 빠른 CPU가 디스크에서 직접 접근하여 데이터를 가져오려고 한다.

- 이러면 CPU가 아무리 빠르다고 한들, 디스크가 데이터를 늦게 주기 때문에 처리 속도는 디스크에 맞춰질 수밖에 없다. 병목이 생기는 것이다. 이를 극복하기 위해 중간에 메모리가 존재하는 것이다. 메모리에는 디스크에서 미리 다음에 CPU가 실행 시킬만한 데이터를 올려두는 것이다. 그럼 CPU의 속도는 메모리의 속도에 맞춰질 것이다.

- 하지만 이것마저도 CPU에게는 여전히 느리다. 그래서 이것을 극복하기 위해 메모리와 CPU사이에 추가적인 메모리를 두는데, 그게 바로 ‘캐시 메모리’이다. 캐시 메모리는 메모리보다 용량은 작지만 훨씬 빠르다.

- 그래서 오늘날 우리가 사용하는 컴퓨터의 구조는 디스크 > 메모리 > 캐시 메모리 > CPU의 순서가 되었다. 이 구조는 결국 처장/처리 장치 사이의 속도 차이를 극복하여 최대한 병목을 줄이기 위해 설계된 것이다.

## 프로세스와 스레드가 사용하는 메모리 영역 설명
- 프로세스는 code, data, heap, stack 영역을 프로세스마다 할당 받아서 사용하고 하나의 프로세스 안에 있는 여러 스레드는 code, data, heap 의 메모리 영역을 공유하고 stack은 각 스레드마다 별도로 사용한다.

**Comment by jerry0339** [comment]
### Context Switching이 뭔가요 ?
CPU에서 여러 실행단위를 돌아가면서 작업을 처리하는 데 이 과정을 **Context Switching**이라 한다.


### 멀티 스레드가 멀티 프로세스보다 빠른 이유가 뭔가요 ?
1. context switching과정에서 캐시메모리 초기화 등 무거운 작업이 진행되고 많은 시간이 소모되는 등 오버헤드가 크다.

2. 프로세스는 각각의 독립된 메모리 영역을 할당 받았기 때문에 프로세스 사이에서 공유하는 메모리가 없어, context switching이 발생하면 캐시에 있는 데이터를 모두 리셋하고 다시 캐시 정보를 불러와야 한다.


### 멀티 스레드가 멀티 프로세스보다 메모리소모도 적고 더 빠르다면 왜 멀티 프로세스를 이용하는 것일까요, 예시가 있을까요?
하나의 프로세스가 죽더라도 다른 프로세스에 영향을 주지 않아 **안정성**이 높다.
예시) google chrome, internet explorer

<br>

**Comment by choiyoungkwon12** [comment]
첫번째 cs 스터디 완료
