### ISSUE TITLE
3번째 : 동기, 비동기, 프로세스 동기화, 메모리 관리 전략

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#3]
일시 : 2022년 01월 17일 오후 1시
<hr>

- 동기와 비동기의 차이
- 프로세스 동기화
   - Critical Section
   - 해결책
      - Lock
      - Semaphores
      - 모니터
- 메모리 관리 전략
   - 메모리 관리 배경
   - Paging
   - Segmentation

**Comment by choiyoungkwon12** [comment]
- 동기와 비동기의 차이를 설명해주세요.

동기 작업이란 작업을 수행하는 두 개 이상의 주체가 서로 동시에 수행하거나, 동시에 끝나거나, 끝나는 동시에 시작할 때를 의미합니다.

시작과 종료를 동시에 하거나, 하나의 작업이 끝나는 동시에 다른 주체가 작업을 시작하면 이는 동기 작업이라고 볼 수 있습니다.

비동기 작업은 두 주체가 서로의 시작, 종료시간과는 관계 없이 별도의 수행 시작/종료시간을 가지고 있을 때를 뜻합니다.

서로 다른 주체가 하는 작업이 자신의 작업 시작, 종료시간과는 관계가 없을 때 비동기라고 부를 수 있습니다.

---

- 임계구역에 여러 스레드가 접근했을 때 일어날 수 있는 문제에 대한 해결책 조건

임계구역에 대한 동기화가 제대로 이루어지지 않으면 은행 계좌 문제처럼 정상적인 결과값이 나오지 않을 수 있다.

이러한 문제가 발생하는 원인은 공통변수(common variable)에 대한 동시 업데이트(concurrent update)) 때문이다.

이를 해결하는 방법은 공통변수에 접근하는 스레드는 하나만 존재하도록 관리해야 한다. 이러한 공통변수 구역을 임계구역(Critical section) 이라고 한다.

임계구역을 해결하기 위해서는 3가지 조건이 만족해야한다.

1. Mutual exclusion(상호배타) - 오직 한 쓰레드만이 진입 가능하다. 한 쓰레드가 임계구역에서 수행 중인 상태에서는 다른 쓰레드는 절대 이 구역에 접근할 수 없다.

2. Progress(진행) - Critical Section 에서 실행중인 프로세스가 없고, 별도의 동작이 없는 프로세스들만 Critical Section 진입 후보로서 참여될 수 있다.

3. Bounded waiting(유한대기) - 같은 프로세스가 임계구역을 독점하지 못하게 한다. 다른 프로세스의 starvaion을 막기 위해 한번 하나의 프로세스가 critical section에 들어가려고 요청한 이후부터는 한정된 대기 횟수 안에 해당 프로세스가 critical section에 들어가야한다.

 ---

- Deadlock이란 무엇인가요?

둘 이상의 프로세스가 서로 상대방에 의해 충족될 수 있는 event를 무한히 기다리는 현상

**Comment by Chaeonida** [comment]
- **임계영역 문제 해결을 위한 기본조건을 설명해주세요** 
Mutual Exclusion(상호 배제)
프로세스 P1 이 Critical Section 에서 실행중이라면, 다른 프로세스들은 그들이 가진 Critical Section 에서 실행될 수 없다.
Progress(진행)
Critical Section 에서 실행중인 프로세스가 없고, 별도의 동작이 없는 프로세스들만 Critical Section 진입 후보로서 참여될 수 있다.
Bounded Waiting(한정된 대기)
P1 가 Critical Section 에 진입 신청 후 부터 받아들여질 때가지, 다른 프로세스들이 Critical Section 에 진입하는 횟수는 제한이 있어야 한다.

- **스와핑의 단점에는 무엇이 있나요** 
문맥교환 비용의 증가
시스템 처리율 감소 :
재배치 이슈 

- **세그먼테이션에 대해 설명해 주세요**
페이징에서처럼 논리 메모리와 물리 메모리를 같은 크기의 블록이 아닌, 서로 다른 크기의 논리적 단위인 세그먼트(Segment)로 분할 사용자가 두 개의 주소로 지정(세그먼트 번호 + 변위) 세그먼트 테이블에는 각 세그먼트의 기준(세그먼트의 시작 물리 주소)과 한계(세그먼트의 길이)를 저장
단점 : 서로 다른 크기의 세그먼트들이 메모리에 적재되고 제거되는 일이 반복되다 보면, 자유 공간들이 많은 수의 작은 조각들로 나누어져 못 쓰게 될 수도 있다.(외부 단편화)

**Comment by jerry0339** [comment]
* **Paging이 나오게된 배경은 무엇인가요 ?**
MMU의 성능을 위해 contiguous allocation방식을 사용하면서 단편화(fragmentation)라는 치명적인 단점이 생겼기 때문이다.
이를 외부 단편화라고 하는데 메모리의 1/3정도가 낭비되는 문제가 있다.

* **외부 단편화, 내부 단편화가 무엇인가요 ?**
**외부 단편화**는 contiguous allocation방식을 사용하면서 생기는 문제이다.
총 메모리 공간을 따져 봤을때 프로세스를 적재할 공간이 충분하지만 남은 공간들이 연속적이지 못하여
즉, 필요한 공간보다 작은 hole들 밖에 없을때 이를 외부 단편화(External Fragmentation)라고 한다.
메모리의 1/3이 낭비되는 치명적인 문제를 야기한다.
**내부 단편화**는 외부 단편화를 해결하기 위하여 페이징(Paging)기법을 사용하면서 생기는 문제이다.
프로세스를 일정한 크기인 페이지(Page)로 잘랐을때 마지막 페이지가 모두 채워지지 못하는 문제가 생긴다.
이를 내부 단편화(Internal Fragmentation)라고 한다. 외부 단편화가 절대 생기지 않으며 내부 단편화가 생긴다고 해도
그 공간의 낭비가 매우 미비하다는 장점이 있다.

* **Paging과 Segmentation의 장단점과 해결방법?**
**Paging**은 프로세스를 물리적으로 일정한 크기인 페이지로 잘라서 메모리에 적재하는 방식이다.
외부 단편화 문제를 완벽하게 해결할 수 있다는 장점이 있다. 
내부 단편화라는 문제가 있긴 하지만 낭비되는 공간이 미비하여 큰 문제가 되지는 않는다.
**Segmentation**은 논리적 내용 단위인 세그먼트의 집합이다.
같은 프로그램을 사용하는 여러 프로세스들이 있다면 해당하는 세그먼트를 메모리에 하나만 적재하여
프로세스의 세그먼트 테이블 코드 영역이 같은 곳을 가리키게 한다. 
이는 보호와 공유의 기능을 수월하게 한다는 장점이 있다.
하지만 세그먼트는 크기가 가변적이기 때문에 외부 단편화 문제가 생기는 큰 문제가 있으므로 사용하기 힘들다.
**따라서 세그먼트를 페이징하는 방법을 사용**한다.

**Comment by choiyoungkwon12** [comment]
👍 👍 👍
