### ISSUE TITLE
4번째 : 가상 메모리, 캐시의 지역성

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#4]
일시 : 2022년 01월 20일 오후 1시
--- 

- 가상 메모리
   - 배경
   - 가상 메모리가 하는 일
   - Demand Paging (요구 페이징)
   - 페이지 교체 알고리즘
- 캐시의 지역성
   - Locality
   - Caching line

**Comment by jerry0339** [comment]
* **TLB(Translation Lookaside Buffer)가 무엇인가요 ?**
페이징(Paging)에서 아래의 그림처럼 페이지와 프레임을 mapping을 위해서 Page Table이 필요하다.
그런데 페이지 테이블의 문제는 크기가 크다는 것이다.
메모리 주소변환을 MMU가 하는데 Page Table의 크기는 MMU에 들어갈 수 없는 크기인것.
메인 메모리에 두자니 메인메모리에 있는 주소를 알기위해 메인메모리에 한번 더 접근하게 되는 비효율적인 문제가 발생
이러한 문제는 **cache memory**에 필요한 page에 대한 정보를 두어 해결하는데 이러한 캐시를 **TLB**(Translation Lookaside Buffer) 이라고 함

* **가상 메모리가 나타나게된 배경이 무엇인가요 ?**
메인 메모리의 공간이 부족하면 빈번하게 swapping과 입출력(I/O)이 이루어짐
메인 메모리보다 큰 프로세스라면 처리하기 까다로움
따라서 프로세스 전체를 메모리에 적재시킬 필요 없이
**필요한 부분만 메모리에 적재**하여 메모리를 효과적으로 관리하는 방법을 고안해 냄

* **캐시 지역성의 전제조건이 무엇인가요 ?**
지역성의 전제 조건으로 프로그램은 모든 코드나 데이터를 균등하게 Access하지 않는다는 특성을 기본으로 한다.

**Comment by Chaeonida** [comment]
- **MMU와 TLB는 무엇인가요?**
MMU: CPU에 코드 실행시, 가상 주소 메모리 접근이 필요할 때, 해당 주소를 물리 주소 값으로 변환해주는 하드웨어 장치
TLB(Translation Lookingside Buffer): 최근 물리 주소로 변환된 가상 주소 정보를 저장하여 페이지 정보를 캐쉬할 수 있는 하드웨어

- **가상주소공간은 무엇인가요?**
 한 프로세스가 메모리에 저장되는 논리적인 모습을 가상메모리에 구현한 공간이다. 프로세스가 요구하는 메모리 공간을 가상메모리에서 제공함으로써 현재 직접적으로 필요치 않은 메모리 공간은 실제 물리 메모리에 올리지 않는 것으로 물리 메모리를 절약할 수 있다.
예를 들어, 한 프로그램이 실행되며 논리 메모리로 100KB 가 요구되었다고 하자. 하지만 실행까지에 필요한 메모리 공간(Heap영역, Stack 영역, 코드, 데이터)의 합이 40KB 라면, 실제 물리 메모리에는 40KB 만 올라가 있고, 나머지 60KB 만큼은 필요시에 물리메모리에 요구한다고 이해할 수 있겠다.

-  **캐시의 지역성에 대해 설명해 주세요**
지역성이란, 데이터 접근이 시간적, 혹은 공간적으로 가깝게 일어나는 것을 의미한다.
지역성의 전제 조건으로 프로그램은 모든 코드나 데이터를 균등하게 Access하지 않는다는 특성을 기본으로 한다.
즉, 지역성(Locality)이란 기억장치 내의 정보를 균일하게 Access하는 것이 아닌 어느 한 순간에 특정 부분을 집중적으로 참조하는 특성이다.
캐시가 효율적으로 동작하려면, 캐시의 적중율(Hit-rate)를 극대화 시켜야 하고 이를 위해서는 캐시에 저장할 데이터가 지역성(Locality)을 가져야 한다.

**Comment by choiyoungkwon12** [comment]
- Demand Paging이란 무엇인가요??
```
프로세스 전체가 메모리 내에 올라와야 하는 메모리 관리 기법 방식의 대안으로 프로세스 전체가 메모리 내에 올라오지 않더라도 실행이 가능하도록 하는 기법을 가상메모리라고 한다.

그 중 요구페이징은 필요한 프로그램만 메모리에 적재하는 방법으로 가상 메모리 시스템에서 많이 사용된다. 
요구 페이징을 사용하는 가상메모리에서는 페이지들이 실행 과정에서 실제로 필요해질 때 적재 된다.
```

- 페이지 폴트란 무엇인가요??
```
페이지 폴트란 프로그램이 자신의 주소 공간(가상메모리공간)에는 존재하지만 시스템의 RAM에는 현재 없는 데이터나 코드에 접근 시도하였을 경우 발생하는 현상을 말한다.
```

- 페이지 교체 알고리즘에서 가장 페이지 폴트를 적게 일으키는 알고리즘은 무엇이고 특징은 무엇인가요??
```
OPT(Optimal Page Replacement)

가장 오랫동안 사용하지 않을 페이지를 교체하기 때문에 가장 낮은 페이지 부재를 보장합니다.
또한 Belady의 변칙과 같은 상황이 일어나지 않습니다.
그러나 OPT는 구현이 어렵기 때문에 다른 알고리즘이 이 OPT알고리즘과 얼마나 비슷한 페이지 부재율이 비슷한지와 같은 비교하는 대상에 사용됩니다.
```
