### ISSUE TITLE
5번째 : 유저/커널 모드, 인터럽트, 데드락

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#5]
# 일시 : 2022년 01월 24일 오후 9시

## 주제
- 유저/커널 모드
- 인터럽트
- 데드락

이외에 운영체제 스터디하면서 미흡했던거 추가로 공부해도 좋을 것 같습니다.

**Comment by Chaeonida** [comment]
- **유저모드와 커널 모드의 차이점에 대해 설명해 주세요**
✔ 유저모드
사용자 애플리케이션의 코드가 실행 됨.
시스템 데이터에 제한된 접근만이 허용, 하드웨어 직접 접근 불가.
시스템 서비스 호출 시 유저모드에서 커널모드로 잠시 전환됨.
스레드는 자신만의 유저모드 스택을 가짐.
✔ 커널모드
모든 시스템 메모리에 접근할 수 있고 모든 CPU명령 실행 가능.
운영체제 코드나 디바이스 드라이버 같은 커널모드 코드를 실행한다.

- **인터럽트 종류에 대해 설명해주세요**

✔ 내부 인터럽트
1.하드웨어 고장(Hardware Interrupt)
- 컴퓨터 고장
- 데이터 전달 과정에서의 비트 오류
- 전원이 나간 경우
2.실행할 수 없는 명령어 : 기억장치에서 인출한 명령어의 비트 패턴이 정의되어 있지 않은 경우
3.명령어 실행 오류 : 나누기 0을 하는 경우
4.사용 권한 위배 : 사용자가 운영체제만 사용할 수 있는 자원에 액세스하는 경우

✔ 외부 인터럽트
1.타이머 인터럽트 : 타이머가 일정한 시간 간격으로 중앙처리장치에게 인터럽트를 요청
2.입출력 인터럽트 : 속도가 느린 입출력장치가 입출력 준비가 완료되었음을 알리기 위해 인터럽트를 요청

-  **데드락의 발생조건에 대해 설명해 주세요**

✔ 상호 배제
한 번에 프로세스 하나만 해당 자원을 사용할 수 있다. 사용 중인 자원을 다른 프로세스가 사용하려면 요청한 자원이 해제될 때까지 기다려야 한다.

✔ 점유 대기
자원을 최소한 하나 보유하고, 다른 프로세스에 할당된 자원을 점유하기 위해 대기하는 프로세스가 존재해야 한다.

✔ 비선점
이미 할당된 자원을 강제로 빼앗을 수 없다(비선점).

✔ 순환 대기
대기 프로세스의 집합이 순환 형태로 자원을 대기하고 있어야 한다.

**Comment by choiyoungkwon12** [comment]
## 1. 인터럽트란 무엇인가??
    - OS는 서로 다른 일을 하는 수많은 하드웨어를 사용한다. 이런 장치들은 동기적으로 구동되는데, 이는 각각 동작이 완료될 때 까지 기다려야하므로 "아무것도 하지 않으면서 바쁜 상태"로 많은 시간을 소비하게된다. 이 때, 인터럽트를 사용하여 한번에 하나의 명령만 수행할 수 있는 CPU의 한계성을 보완할 수 있다.
  
    - 프로그램을 실행하는 도중에 예기치 않은 상황이 발생할 경우, 현재 실행중인 작업을 중단하고 발생된 상황을 처리한 후, 다시 실행중인 작업으로 복귀하는 것

## 2. 인터럽트 처리중에 또다른 인터럽트가 발생하는 경우는 어떻게 되는가?
   - 원직적으로는 인터럽트 처리중에 또 다른 인터럽트의 처리를 허용하지 않는다.
  앞서 변경중이던 데이터를 또다른 인터럽트가 발생해 처리하게 되면 의도하지 않은 결과값으로 바뀔 수 있기 때문이다.

   - 예외적인 경우가 존재한다.
  인터럽트마다 중요도가 다르다.
  상대적으로 낮은 중요도를 가진 인터럽트를 처리하는 도중 높은 중요도의 인터럽트 발생을 허용한다.
 
##  3. 데드락 발생 조건과 처리방법
 
공유 자원 할당 시, 데드락의 4가지 조건 중, 어느 하나가 만족되지 않도록 하는 것
 
Mutual Exclusion (상호 배제)
- 매 순간 하나의 프로세스만이 자원을 사용할 수 있음
=> 여러 개의 프로세스가 공유 자원을 사용할 수 있도록 한다

No Preemption (비선점)
- 프로세스는 자원을 스스로 내놓을 뿐 강제로 빼앗기지 않음
=> Save & Restore 이 가능한 자원에서 선점(Preemption)을 허용한다

Hold and Wait (점유 대기)
- 자원을 가진 프로세스가 다른 자원을 기다릴 때, 보유 자원을 놓지 않고 
갖고 있음
=>프로세스 시작 시, 모든 자원을 할당한다
=> 자원이 필요한 경우, 보유 자원을 놓는다

Circular Wait (순환 대기)
- 자원을 기다리는 프로세스간, 사이클이 형성되어야함
=> 할당 순서를 정하여, 정해진 순서대로 자원을 할당한다

**Comment by jerry0339** [comment]
* **인터럽트 벡터가 무엇인가요 ?**
인터럽드 발생시 처리해야 할 인터럽트 서비스 루틴(ISR)의 주소를
인터럽트 별로 보관하고 있는 테이블이다.


* **데드락의 발생조건이 무엇인가요 ?**
데드락의 발생조건은 데드락의 필요조건이다.
1. 상호 배제 (Mutual Exclusion)
동기화를 만족시키기 위한 조건과 같다. 
하나의 프로세스가 자원을 사용할 경우 다른 프로세스는 그 자원을 사용할 수 없는 것을 의미

2. 점유와 대기 (Hold and wait)
프로세스가 이미 어떤 자원을 점유하고 있으면서 다른 종류의 자원을 요구하는 것을 의미

3. 비선점 (No preemption)
임의의 프로세스가 자원을 할당 받은 상태에서 다른 프로세스가 이 자원을 뺏어서 사용할 수 없는 형태를 의미

4. 환형대기 (circle wait)
프로세스와 자원들이 원형을 이루며, 
각 프로세스는 자신에게 할당된 자원을 가지면서 상대방 프로세스의 자원을 상호 요청하는 경우를 의미


* **데드락의 해결방법 ?**
1. 예방 (prevention)
위의 데드락 발생조건 4가지 중 하나라도 발생하지 않도록 사전에 예방

2. 회피 (avoidance)
데드락이 빠질 가능성이 있는지 없는지 운영체제가 검사하고 괜찮은 경우만 자원을 할당하여 데드락을 회피
ex) 은행원 알고리즘

3. 탐지 (Detection)
교착상태 발생을 허용하고 발생시 원인을 규명하여 해결
ex) 자원할당 그래프

4. 회복 (recovery)
교착상태 프로세스들을 모두 중지 또는 교착상태가 해결될 때까지 프로세스 하나씩 중지(환형대기 배제)

5. 무시 (Do Nothing, ignore)
운영체제가 교착상태를 무시함. 개발자가 데드락에 빠질 가능성이 없도록 프로그램을 설계해야 함

**Comment by choiyoungkwon12** [comment]
👍
