### ISSUE TITLE
6번째 : OSI 7 계층

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#6]
### 📆  일시 : 2022-01-27 오후 1시

---

### 📖  주제 :  OSI 7 계층

**Comment by choiyoungkwon12** [comment]
osi 7 layer 중에서 암,복호화는 어디서 할까요?
- 표현층에서 합니다.

tcp/ip 모델은 어떻게 나눠져 있나요?
- osi 7 layer의 application layer, Transport layer, Network layer, Data Link Layer, Physical Layer가 있습니다.

osi 7 layer의 동작은 어떻게 하나요?
- 전송 시 7계층에서 1계층으로 각각의 층마다 인식할 수 있어야 하는 헤더를 붙임(캡슐화)
- 수신 시 1계층에서 7계층으로 헤더를 떼어냄(디캡슐화)
- 출발지에서 데이터가 전송될 때 헤더가 추가되는데 2계층에서만 오류제어를 위해 꼬리부분에 추가됌
- 물리계층에서 1, 0 의 신호가 되어 전송매체 (동축케이블, 광섬유 등)을 통해 전송

**Comment by Chaeonida** [comment]
- 물리적인 연결을 통하여 인접한 두 장치 간의 신뢰성 있는 정보 전송을 담당하는 구역은 어디인가요?
- 표현계층의 세가지 기능을 설명해주세요

**Comment by jerry0339** [comment]
* OSI 7계층은 왜 만들어 졌을까요 ?
* TCP/UDP 프로토콜은 어느 계층에 속할까요 ?
