### ISSUE TITLE
7번째 : 네트워크 TCP/IP , HTTP

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#7]
# 일시 : 2022-02-03

# 주제

TCP 3 way handshake & 4 way handshake

TCP/IP 흐름제어 & 혼잡제어

UDP

대칭키 & 공개키

HTTP & HTTPS
-  HTTP status code
 - HTTP METHOD
  - HTTP 특징
  - HTTP와 HTTPS의 차이

HTTP 1.1 vs HTTP 2.0 vs HTTP 3.0
  - HTTP1.0 과 HTTP1.1 차이

**Comment by Chaeonida** [comment]
- **Q. TCP의 연결 설정 과정(3단계)과 연결 종료 과정(4단계)이 단계가 차이나는 이유?**

 A. Client가 전송할 데이터가 없다고해도 Server에서 보내야하는 데이터가 아직 남아있을 수 있기때문에 우선 FIN에 대한 ACK를 먼저 보내고 남은 데이터 전송 후에 FIN을 보낸다.

- **Q. 만약 Server에서 FIN 플래그를 전송하기 전에 전송한 패킷이 Routing 지연이나 패킷 유실로 인한 재전송 등으로 인해 FIN 패킷보다 늦게 도착하는 상황이 발생하면 어떻게 될까?** 

A. Client에서 세션을 종료시킨 후 늦게 도착하는 패킷은 drop되고 데이터는 유실된다. 이런 상황에 대비하여 Client는 Server로부터 FIN을 수신하고 일정시간(default 240sec)동안 세션을 남겨두고 잉여 패킷을 기다린다. (TIME_WAIT 과정)

- **Q.  흐름제어(Flow Control)와 혼잡제어(Congestion Control)이란?**

흐름제어는 데이터를 송신하는 곳과 수신하는 곳의 데이터 처리 속도를 조절하여 수신자의 버퍼 오버플로우를 방지하는 것입니다. 예를 들어 송신하는 곳에서 감당이 안되게 데이터를 빠르게 많이 보내면 수신자에서 문제가 발생하기 때문입니다.

혼잡제어는 네트워크 내의 패킷 수가 넘치게 증가하지 않도록 방지하는 것입니다.

- **Q TCP는 패킷을 어떻게 추적 및 관리하나요?**

TCP는 데이터는 패킷단위로 나누어 같은 목적지(IP계층)으로 전송된다.  A,B,C라는 패킷에 1,2,3이라는 번호를 부여하여 패킷의 분실 확인과 같은 처리를 하여 목적지에서 재조립을 합니다. 이런 방식으로 TCP는 패킷을 추적하며, 나누어 보내진 데이터를 받고 조립을 할 수 있습니다.

**Comment by choiyoungkwon12** [comment]
HTTP와 HTTPS 통신의 차이점이 뭔가요??
- HTTPS는 HTTP 통신에서 SSL 통신을 하느냐 안하느냐 차이로 HTTP는 일반적으로 평문 통신을 하게 되는데 중간에 탈취 당하거나 하면 위험 할 수 있어서 통신할 떄 SSL을 거쳐서 암호화 및 복호화를 하게 됩니다.

HTTP 1.0과 HTTP 1.1의 차이점을 알려주세요.
- HTTP의 특징으로 비 연결성이 있는데 요청과 응답이 일어날 때마다 3-way handshake와 4-way handshake를 하면 비효율적이고 느리기 때문에 일정 기간동안 커넥션을 유지하는 persistent-connection이 가장 큰 차이이다.

TCP 와 UDP의 차이점을 알려주세요.
- TCP는 신뢰성 있는 통신을 하기 때문에 3-way handshake, 4-way handshake 과정을 거치고 데이터를 보내면 응답을 하고 UDP는 신뢰성 있는 통신을 하는 것이 아닌 대신 속도가 빠르다.

**Comment by jerry0339** [comment]
### **1. TCP/UDP 가 생겨난 이유가 무엇일까요 ?**
* IP의 한계
    * 비연결성 : 패킷을 받을 대상이 없거나 서비스 불능 상태여도 패킷 전송
    * 비신뢰성 : 패킷의 순서가 바뀌거나 패킷이 누락될 수 있음
    * 프로그램의 구분 : 같은 IP를 사용하는 서버에서 통신하는 어플리케이션이 둘 이상? (Port 관련)
    * TCP, UDP가 나오게된 계기

***
 
### **2. HTTP/1.0 과 HTTP/1.1 의 차이점은 무엇일까요 ?**
**커넥션 유지**
~~~
HTTP를 이용한 데이터 전달은 TCP세션 기반에서 이루어진다.
HTTP 1.1에서는 1.0과는 달리 TCP세션을 지속적으로 유지할 수 있는데에 차이가 있다.
~~~

**파이프라이닝 (Pipelining)**
~~~
HTTP 요청은 순차적으로 이루어 지는데 파이프라이닝을 이용하면
아래의 그림처럼 같은 TCP세션에서 동시에 요청을 여러개 보내고 이에 대한 각각의 응답을 받아 처리할 수 있다.
~~~

**호스트 헤더**
~~~
HTTP 1.0 에서는 하나의 IP에 여러 도메인을 운영할 수 없지만
HTTP 1.1 부터는 Host 헤더의 추가를 통해 버츄얼 호스팅이 가능해 졌다.
~~~

**강력한 인증 절차**
~~~
HTTP 1.0에서도 클라이언트의 인증을 요구하는 헤더(www-authentication)는 지원되어 왔으나
클라이언트와 서버 사이에 프록시가 위치하는 경우 사용자의 인증을 요구할 수 있는 방법이 없었다.
HTTP 1.1에서는 아래의 두 헤더를 통해 해결이 가능하다.

• proxy-authentication
• proxy-authorization
~~~

***

### **3. HTTP METHOD의 멱등성이 뭔가요 ?**
~~~
동일한 요청을 한 번 보내는 것과 여러 번 연속으로 보내는 것이 같은 효과를 지니고,
서버의 상태도 동일하게 남을 때, 해당 HTTP 메서드가 멱등성을 가졌다고 말합니다. 
~~~

**멱등성**
* GET, PUT, DELETE 멱등함 -> 특정 요청성공시 매번 같은 결과
* POST , PATCH는 멱등하지 않음 
    * POST : 특정 POST요청을 계속하면 계속해서 데이터가 추가됨
    * PATCH : 멱등하게 설계할 수도 있지만, 특정값에 +10을 하는 요청이라면 요청 반복시 결과가 계속해서 변경됨

**Comment by choiyoungkwon12** [comment]
👍 👍 👍 👍
