### ISSUE TITLE
8번째 : 네트워크 REST, Web server, Was, COOKIE & SESSION

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#8]
# 일시 : 2022-02-08 오후 4시

# 주제 :

- REST, RESTFUL, REST API

- Web Server VS WAS

- COOKIE & SESSION

**Comment by Chaeonida** [comment]
- **Q. WAS만 써도 되나요?**
A. WAS는 DB 조회 및 다양한 로직을 처리하는데 집중해야 한다. 따라서 단순한 정적 컨텐츠는 웹서버에게 맡기며 기능을 분리시켜 서버 부하를 방지한다. 만약 WAS가 정적 컨텐츠 요청까지 처리하면, 부하가 커지고 동적 컨텐츠 처리가 지연되면서 수행 속도가 느려지고 이로 인해 페이지 노출시간이 늘어나는 문제가 발생하여 효율성이 크게 떨어진다.
웹 서버를 WAS 앞에 두고 필요한 WAS들을 Wev Server에 플러그인 형태로 설정하면 더욱 효율적인 분산 처리가 가능하다.

- **Q. 세션을 쓰면되는데 굳이 쿠키를 사용하는 이유?**
A. 세션이 쿠키에 비해 보안도 높은 편이나 쿠키를 사용하는 이유는
세션은 서버에 저장되고, 서버자원을 사용하기 때문에 사용자가 많을 경우 소모되는 자원이 상당하다.
이러한 자원관리 차원에서 쿠키와 세션을 적절한 요소 및 기능에 병행 사용하여,
서버 자원의 낭비를 방지하며 웹사이트의 속도를 높일 수 있다.

-  **Q. REST의 구성 요소**
A.  
1. 자원(Resource) - URI
모든 자원에는 고유한 ID가 존재하고, 이 자원은 Server에 존재 
2. 표현 ( Representation of Resource )
Client와 Server가 데이터를 주고받는 형태로 JSON, XML, TEXT, RSS 등이 있다.
JSON, XML을 통해 데이터를 주고 받는 것이 일반적
3. 행위(Verb) - Method
HTTP 프로토콜의 Method를 사용합니다.
HTTP 프로토콜은 GET, POST, PUT, PATCH, DELETE의 Method를 제공합니다. ( CRUD )

**Comment by choiyoungkwon12** [comment]
- REST가 뭔가요??
  - REST란 웹의 장점을 최대한 활용할 수 있는 아키텍처로 자원(Resource)의 표현(Representation)에 의한 상태 전달을 나타내며
  - HTTP URI(Uniform Resource Identifier)를 통해 자원(Resource)를 명시하고, HTTP Method를 통해 해당 자원에 대한 CRUD Operation을 적용하는 것을 의미합니다.

- 쿠키와 세션을 사용하게 된 이유가 뭔가요??
  - HTTP의 특징인 비연결성과 무상태성이 있는데 실제로는 데이터를 유지해야 하는 경우가 많습니다.
  - 그래서 나온게 쿠키와 세션입니다.

- WAS란 무엇인가요??
  - 인터넷 상에서 HTTP 프로토콜을 통해 사용자 컴퓨터나 장치에 애플리케이션을 수행해주는 미들웨어로서, 주로 동적 서버 컨텐츠를 수행하는 것으로 웹 서버와 구별이 되며, 주로 데이터베이스 서버와 같이 수행
  - 자바에서는 동적인 프로그래밍을 하기 위해 사용하는 것을 서블릿 이라고 하기 때문에 서블릿 컨테이너 라고도 합니다.

**Comment by jerry0339** [comment]
* **REST를 한줄로 표현하면?**
URI와 HTTP를 이용한, 통신 목적의 아키텍처 스타일이다

<br>

* **쿠키와 세션의 차이점은 무엇인가요 ?**
1. 가장 큰 차이점은 사용자의 정보가 저장되는 위치
    * 쿠키는 클라이언트에 저장
    * 세션은 서버에 저장
2. 만료시점
    * 쿠키는 생성시 만료일을 설정, 브라우저가 종료되어도 삭제되지 않을 수 있음
    * 세션은 쿠키와 같이 만료일을 설정할 수 있지만 브라우저 종료시 삭제됨
3. 쿠키가 세션보다 빠르다.
4. 세션이 쿠키보다 보안이 좋다.

<br>

* **WAS의 역할은 무엇일까요 ?**
1. 웹서버와 WAS로 기능을 분리하여 **서버 부하를 방지**
2. 물리적으로 분리하여 **보안강화**
3. **여러대의 WAS를 연결** 가능
    * 로드 밸런싱
    * fail over(장애 극복), fail back 처리에 유리
    * 무중단 배포 운영
4. **여러 웹 어플리케이션 서비스 가능** - 하나의 웹서버에서 Java서버, C#서버, PHP서버 등을 서비스 가능
