### ISSUE TITLE
9번째 : 네트워크 (CORS, JWT)

### ISSUE THREAD

**Issue by choiyoungkwon12** [study-for-interview/cs-study#9]
# 일시  : 2022-02-10 오후 8시

# 주제 :
- CORS
- JWT

**Comment by Chaeonida** [comment]
- **Q. JWT 동작 과정은 어떻게 되나요?** 

A. 
1. 사용자가 id와 password를 입력하여 로그인을 시도합니다.
2. 서버는 요청을 확인하고 secret key를 통해 Access token을 발급합니다.
3. JWT 토큰을 클라이언트에 전달 합니다.
4.클라이언트에서 API 을 요청할때 클라이언트가 Authorization header에 Access token을 담아서 보냅니다.
5.서버는 JWT Signature를 체크하고 Payload로부터 사용자 정보를 확인해 데이터를 반환합니다.
6. 클라이언트의 로그인 정보를 서버 메모리에 저장하지 않기 때문에 토큰기반 인증 메커니즘을 제공합니다. 인증이 필요한 경로에 접근할 때 서버 측은 Authorization 헤더에 유효한 JWT 또는 존재하는지 확인합니다. 

- **Q. JWT 구조는 어떻게 되나요?**
A. 
1.  Header(헤더)
토큰의 헤더는 typ과 alg 두 가지 정보로 구성된다.
alg: 헤더(Header)를 암호화 하는 것이 아니고, Signature를 해싱하기 위한 알고리즘을 지정하는 것이다.
typ: 토큰의 타입을 지정
2. Payload
토큰에 담을 정보가 들어있습니다. 여기에 담는 정보의 한 ‘조각’ 을 클레임(claim) 이라고 부르고, 이는 name / value 의 한 쌍으로 이뤄져있습니다. 토큰에는 여러개의 클레임 들을 넣을 수 있습니다
3. 서명 (signature)
JSON Web Token 의 마지막 부분은 바로 서명(signature) 입니다. 이 서명은 헤더의 인코딩값과, 정보의 인코딩값을 합친후 주어진 비밀키로 해쉬를 하여 생성합니다.

- **Q. CORS 동작 과정**
A. 기본적으로 웹 클라이언트 어플리케이션이 다른 출처의 리소스를 요청할 때는 HTTP 프로토콜을 사용하여 요청을 보내게 되는데, 이때 브라우저는 요청 헤더에 Origin이라는 필드에 요청을 보내는 출처를 함께 담아보낸다.
이후 서버가 이 요청에 대한 응답을 할 때 응답 헤더의 Access-Control-Allow-Origin이라는 값에 “이 리소스를 접근하는 것이 허용된 출처”를 내려주고, 이후 응답을 받은 브라우저는 자신이 보냈던 요청의 Origin과 서버가 보내준 응답의 Access-Control-Allow-Origin을 비교해본 후 이 응답이 유효한 응답인지 아닌지를 결정한다.

**Comment by jerry0339** [comment]
* **JWT란 ?**
JWT (JSON Web Token)는 Json 포맷을 이용하여 사용자에 대한 속성을 저장하는 Claim 기반의 Web Token이다.
가볍고(compact) 자체적으로 필요한 정보를 담는(self-contained) 방식으로, 
서버와 클라이언트 사이에서 JSON 객체를 빠르고 안전하게 전달한다.

* **CORS 란 ?**
브라우저에서 다른 출처의 리소스를 공유하는 방법
출처의 비교는 URL의 구조에서 Protocal, Host, Port가 같은지 확인해야 한다.

* **동일 출처 정책(SOP)란 ?**
동일 출처 정책은 다른 출처의 리소스의 접근을 금지하는것이다.
XSS나 XSRF등 보안 취약점을 노린 공격을 방어할 수 있다는 장점이 있다.
다른 서버에서의 데이터를 요청하는것과 같이 외부 리소스를 참고하는것이 빈번하기 때문에 그 방법이 존재해야 한다.

**Comment by choiyoungkwon12** [comment]
- JWT 구조는 어떻게 되나요??
  - header, payload, signature로 구성됩니다.
  - header에는 보통 토큰의 타입이나, 서명 생성에 어떤 알고리즘이 사용되었는지 저장합니다.
  -  payload에는 보통 Claim이라는 사용자에 대한, 혹은 토큰에 대한 property를 key-value의 형태로 저장합니다. Claim이라는 말 그대로 토큰에서 사용할 정보의 조각인 셈입니다.
  - signature는 암호화 되어있고 서버에서 사용하는 개인키로 복호화 한다.
  - 지금까지 Header와 Payload를 보여줄 때는 인코딩 되어있던 값들을 JWT에 담겨있는 것처럼 디코딩된 상태를 사용합니다.
  - 서버가 가지고 있는 개인키를 가지고 Signature를 복호화한 다음 base64UrlEncode(header)가 JWT의 header값과 일치한 지, base64UrlEncode(payload) 와 일치한 지 확인하여 일치한다면 인증을 허용합니다.

- JWT를 토큰이 탈취당하면 만료될 때까지 대처가 불가능한데 해결할 수 있는 최소한의 방법이 무엇인가요??
  - exp를 짧게 가져갈 수 있다.
  - Refresh Token을 JWT 발급 시 같이 발긍해서 짧은 만료시간에 대한 불편함을 해결할 수 있다.

- CORS Preflight의 동작방식이 어떻게 되나요??
  - 브라우저는 서버에게 예비 요청을 먼저 보내고, 서버는 이 예비 요청에 대한 응답으로 현재 자신이 어떤 것들을 허용하고, 어떤 것들을 금지하고 있는지에 대한 정보를 응답 헤더에 담아서 브라우저에게 다시 보내주게 된다.
 
  - 이후 브라우저는 자신이 보낸 예비 요청과 서버가 응답에 담아준 허용 정책을 비교한 후, 이 요청을 보내는 것이 안전하다고 판단되면 같은 엔드포인트로 다시 본 요청을 보내게 된다. 이후 서버가 이 본 요청에 대한 응답을 하면 브라우저는 최종적으로 이 응답 데이터를 자바스크립트에게 넘겨준다.
